--- 
lines: 
- BY PAUL TULLIS
- |
  

- "No. 1: One should not yell at one's personal assistant too much."
- |
  

- He really is trying.
- |
  

- At least he looks like he's working hard, anyway.
- "No. 2: Always be sure to attend the  Vanity Fair  party on Oscar night."
- |
  

- The studio parties are fine, and if Arnold has a movie out or soon-to-be-released, definitely acquiesce and go to that studio's party first, but never ever miss the  Vanity Fair  party.
- |
  

- They have the best hors d'oeuvres, the most stars, and all the top-drawer celebrity sycophants with microphones and cameras outside.
- "No. 3: Don't be afraid to cash in favors just because you are who you are."
- |
  

- A $143 million box office is  nothing  these days, anyway.
- |
  

- "Reminder to self: call Jay Leno's assistant and let him know he's gonna owe you for huge ratings boost on 8/7/03 program."
- |
  

- Same goes for NBC at contract time.
- |
  

- "No. 4: Rubies go best with my eye color and skin tone."
- |
  

- Diamonds are always fine, of course, but never in profusion, except on Oscar night or when attending a black-tie-optional (or more formal) benefit with the word "gala" on the invitation. (The irony of wearing $50,000-worth of jewelry while ostensibly aiding those less fortunate than I shall be entirely lost on me.) Emeralds make my skin look yellow and highlight the freckles on my d&eacute;colletage and that's just yucky. Rubies, on the other hand, make me look tan and glamorous and not too showy when I'm just hanging out and not  trying  to be showy, if you know what I mean.
- "No. 5: Stay out da ghetto."
- "No. 6: Don't take the Hummer to the grocery store."
- |
  

- The parking spaces are too small.
- |
  

- And don't take the Porsche, either, the back seat is too small for anything more than three grocery bags, and there's an engine where the trunk is supposed to be.
- |
  

- "Actually, fuck it, don't go to the grocery store at all: send the nanny."
- "No. 7: Christmas at home in Santa Monica with the family, Hyannisport for Fourth of July, St."
- |
  

- Bart's or Mustique for New Year's.
- |
  

- Always.
- |
  

- It gives the children a sense of stability, and that's so important at this age.
- "No. 8: There's no legitimate reason that husband's campaign against \"special interests\" should extend into the boudoir."
- "No. 9: Nagging feelings of guilt about having completely betrayed my family's values and history of service to the Democratic Party by marrying a Republican now trying to undo the results of an election and become Governor of California by cynically exploiting an obscure law enacted by Progressives, can be eradicated by simply remembering that love conquers all."
- |
  

- Just think of James Carville and Marlee Matlin.
- "No. 10: Don't even waste time trying to make nice with Diane Sawyer."
- |
  

- She is, like, such a bitch.
- |
  

- Same goes for Katie Couric.
- |
  

- And Paula Zahn.
- |
  

- That chick on CBS  The Early Show,  too, whatshername.
- |
  

- Not Oprah though.
- |
  

- I just love Oprah.
- |
  

- She really is a true friend.
- |
  

downcase_name: ....more.things.i.wish.i..ia.shriver_by.paul.tulli
author: By Paul Tullis
title: "\"10 More Things I Wish I'd Known Before I Went Out Into the Real World \xE2\x80\x94 The Real World, That is, As Experienced by a Kennedy Who Married Arnold Schwarzenegger,\" By Maria Shriver"
text: |-
  BY PAUL TULLIS
  - - - -
  No. 1: One should not yell at one's personal assistant too much. He really is trying. At least he looks like he's working hard, anyway.
  No. 2: Always be sure to attend the  Vanity Fair  party on Oscar night. The studio parties are fine, and if Arnold has a movie out or soon-to-be-released, definitely acquiesce and go to that studio's party first, but never ever miss the  Vanity Fair  party. They have the best hors d'oeuvres, the most stars, and all the top-drawer celebrity sycophants with microphones and cameras outside.
  No. 3: Don't be afraid to cash in favors just because you are who you are. A $143 million box office is  nothing  these days, anyway. (Reminder to self: call Jay Leno's assistant and let him know he's gonna owe you for huge ratings boost on 8/7/03 program. Same goes for NBC at contract time.)
  No. 4: Rubies go best with my eye color and skin tone. Diamonds are always fine, of course, but never in profusion, except on Oscar night or when attending a black-tie-optional (or more formal) benefit with the word "gala" on the invitation. (The irony of wearing $50,000-worth of jewelry while ostensibly aiding those less fortunate than I shall be entirely lost on me.) Emeralds make my skin look yellow and highlight the freckles on my d&eacute;colletage and that's just yucky. Rubies, on the other hand, make me look tan and glamorous and not too showy when I'm just hanging out and not  trying  to be showy, if you know what I mean.
  No. 5: Stay out da ghetto.
  No. 6: Don't take the Hummer to the grocery store. The parking spaces are too small. And don't take the Porsche, either, the back seat is too small for anything more than three grocery bags, and there's an engine where the trunk is supposed to be. Actually, fuck it, don't go to the grocery store at all: send the nanny.
  No. 7: Christmas at home in Santa Monica with the family, Hyannisport for Fourth of July, St. Bart's or Mustique for New Year's. Always. It gives the children a sense of stability, and that's so important at this age.
  No. 8: There's no legitimate reason that husband's campaign against "special interests" should extend into the boudoir.
  No. 9: Nagging feelings of guilt about having completely betrayed my family's values and history of service to the Democratic Party by marrying a Republican now trying to undo the results of an election and become Governor of California by cynically exploiting an obscure law enacted by Progressives, can be eradicated by simply remembering that love conquers all. Just think of James Carville and Marlee Matlin.
  No. 10: Don't even waste time trying to make nice with Diane Sawyer. She is, like, such a bitch. Same goes for Katie Couric. And Paula Zahn. That chick on CBS  The Early Show,  too, whatshername. Not Oprah though. I just love Oprah. She really is a true friend.
  &nbsp;
  &nbsp;
date: 8/11/03
article_url: http://mcsweeneys.net/2003/08/11tenthings.html
article_size: 2856
