--- 
lines: 
- |
  

- Presidential
- Stump Speech of
- Billy Bush, Cousin of
- George W. Bush and
- Access Hollywood
- Entertainment
- Reporter.
- |
  

- BY  TEDDY WAYNE
- |
  

- Welcome to Omaha, Nebraska, for my stump speech for tonight, October 7, 2008!
- Which Middle Eastern country renowned for its figs and mulberries is stockpiling Nigerian yellowcake and harboring known Al Qaeda cells?
- Which West Coast state whose governor's re-election was not "Terminated" needs bolstered border control to cope with a rising tide of illegal immigrants?
- What New Deal relic with double initials is in need of increased privatization, allowing up to five percentage points of income to be diverted to individual accounts, or it will become bankrupt by 2057?
- The answers to these critical policy questions and much, much more, after I first show you what a folksy, outgoing, hyperactive guy I am!
- "When I was earning my bachelor's degree at Colby College in international studies and government, I thought the purpose of my degree was to enjoy life as a bachelor\x97not run for president of the United States!"
- |
  

- But now I'm married  and  I'm running for president!
- |
  

- Can you believe that not only have I found a woman who's willing to put up with my completely irritating peppiness and star-fucking addiction but, according to the latest Gallup poll, apparently 53 percent of Americans are, too!
- "Stop: domestic-policy time!"
- |
  

- "School choice is necessary and effective\x97I'll \"vouch\" for it! A recent national study by the Hoover Institution\x97because politics don't take place in a vacuum!\x97reveals that children in voucher schools are 16 percent more likely than students in nonvoucher public schools to graduate from high school and 11 percent more likely to attend a four-year college! U can't educate this! (\"U\" being nonvoucher public schools, and \"this\" meaning students who attend these schools."
- |
  

- "Hit me, baby, one more time\x97is what my Democratic counterpart is begging the terrorists to do if he pursues his proposed plan of slowly building a Middle Eastern coalition rather than maintaining the policy of strategic pre-emptive warfare that has proven so successful over the past five and a half years in Afghanistan, Iraq, Iran, Syria, Jordan, Iraq again, Egypt, North Korea, Iraq a third time, and Canada!"
- |
  

- "My running mate, Ryan Seacrest, and I agree on this wholeheartedly: We must smoke out terrorists and hunt them down wherever they are, and J. Lo's new do at this year's Oscars was a major \"don't\"! And if the job requires diplomacy, which I hope will be used only as a last resort after all other options of aggression have been exhausted, my skills have been honed from years of asking tough questions to the likes of Carmen Electra, Demi Joel Osment, and Mary-Kate and/or Ashley Olsen. This is not the kind of thing you learn in politician school."
- Let's pause for a moment to reflect on what it means to be an American in the 21st century, and to wish a happy birthday to Secretary of Transportation Norman Y. Mineta, still truckin' at 77; Chief Justice Antonin Scalia, who "over"-turns 72 today; and a very happy 66th to freshly pardoned "Kenny Boy" Lay!
- "My fellow Americans, I make this solemn pledge to you: If you elect me your 44th president, thereby giving me the nickname \"44\" within the Bush clan, which would be so cool, I will get Nick and Jessica to sing a duet at my inauguration. They owe me bigtime\x97I got them back together after  Newly Estranged ."
- Oh, my God, there's Majority Leader Bill Frist!
- |
  

- Bill!
- |
  

- Bill!
- |
  

- Over here!
- |
  

- Up on the podium!
- |
  

- Bill, who are you wearing?
- |
  

- What new pro-big-business and civil-liberties-curtailing initiatives do you have coming down the pipeline?
- |
  

- Turn around, let's see the back!
- |
  

- Are you and Hastert cooking up any slogans that convince the working class to vote against its own interests?
- |
  

- Love ya!
- |
  

- In a totally heterosexual way that promotes marriage between only a man and a woman, of course, as the 28th Amendment dictates, but that still recognizes our bond in Christian brotherhood!
- |
  

- By invoking my total faith in and fealty to the 28th Amendment, my preceding comment about loving another man cannot be interpreted as sexually or romantically inclined in any way, and therefore I cannot be summarily detained or executed!
- "That's a wrap for tonight, Class II and III Vassals of Nebraska, but make sure you tune in for my first debate with my opponent tomorrow night\x97assuming he is not assassinated before then for some unknown reason by henchmen totally unconnected with me or my family\x97in the Independent Nation of FOX/Florida under the auspices of His Majesty Emperor Jeb!"
- |
  

- "It's at 10/9 Central Bush Time, so you can still catch  CSI: Eugene  and  Ross !"
- |
  

- "I'm Billy Bush and I'm running for president\x97that still sounds weird to me, like it should be in a movie about a guy who's running for president!"
- |
  

- I wonder who'll play me in the movie version of my life after I heroically rise to the challenge presented by the terrible terrorist attacks by liberal Hollywood atheists that may or may not befall our country on July 29, 2009, or "7/29," which will lead to martial law in Hollywood and the transfer of movie production to the government? Wait, that means I'd be in charge, so I could play myself! Then I could interview myself at the premiere! I'll leave you now with some subliminal mind-control messages playing under the new Jamie Lynn Spears campaign-exclusive hit song "Flat Tax (featuring Lil Jon)"!
- |
  

downcase_name: .....presidential.stump.s.t.reporter_by.teddy.wayn
author: By Teddy Wayne
title: 2008 Presidential Stump Speech of Billy Bush, Cousin of George W. Bush and Access Hollywood Entertainment Reporter
text: "- - - -\n\
  2008\n\
  Presidential\n\
  Stump Speech of\n\
  Billy Bush, Cousin of\n\
  George W. Bush and\n\
  Access Hollywood\n\
  Entertainment\n\
  Reporter. \n\n\n\n BY  TEDDY WAYNE\n\
  - - - -\n\
  Welcome to Omaha, Nebraska, for my stump speech for tonight, October 7, 2008!\n\
  Which Middle Eastern country renowned for its figs and mulberries is stockpiling Nigerian yellowcake and harboring known Al Qaeda cells?\n\
  Which West Coast state whose governor's re-election was not \"Terminated\" needs bolstered border control to cope with a rising tide of illegal immigrants?\n\
  What New Deal relic with double initials is in need of increased privatization, allowing up to five percentage points of income to be diverted to individual accounts, or it will become bankrupt by 2057?\n\
  The answers to these critical policy questions and much, much more, after I first show you what a folksy, outgoing, hyperactive guy I am!\n\
  When I was earning my bachelor's degree at Colby College in international studies and government, I thought the purpose of my degree was to enjoy life as a bachelor\x97not run for president of the United States! But now I'm married  and  I'm running for president! Can you believe that not only have I found a woman who's willing to put up with my completely irritating peppiness and star-fucking addiction but, according to the latest Gallup poll, apparently 53 percent of Americans are, too!\n\
  Stop: domestic-policy time! School choice is necessary and effective\x97I'll \"vouch\" for it! A recent national study by the Hoover Institution\x97because politics don't take place in a vacuum!\x97reveals that children in voucher schools are 16 percent more likely than students in nonvoucher public schools to graduate from high school and 11 percent more likely to attend a four-year college! U can't educate this! (\"U\" being nonvoucher public schools, and \"this\" meaning students who attend these schools.)\n\
  Hit me, baby, one more time\x97is what my Democratic counterpart is begging the terrorists to do if he pursues his proposed plan of slowly building a Middle Eastern coalition rather than maintaining the policy of strategic pre-emptive warfare that has proven so successful over the past five and a half years in Afghanistan, Iraq, Iran, Syria, Jordan, Iraq again, Egypt, North Korea, Iraq a third time, and Canada! My running mate, Ryan Seacrest, and I agree on this wholeheartedly: We must smoke out terrorists and hunt them down wherever they are, and J. Lo's new do at this year's Oscars was a major \"don't\"! And if the job requires diplomacy, which I hope will be used only as a last resort after all other options of aggression have been exhausted, my skills have been honed from years of asking tough questions to the likes of Carmen Electra, Demi Joel Osment, and Mary-Kate and/or Ashley Olsen. This is not the kind of thing you learn in politician school.\n\
  Let's pause for a moment to reflect on what it means to be an American in the 21st century, and to wish a happy birthday to Secretary of Transportation Norman Y. Mineta, still truckin' at 77; Chief Justice Antonin Scalia, who \"over\"-turns 72 today; and a very happy 66th to freshly pardoned \"Kenny Boy\" Lay!\n\
  My fellow Americans, I make this solemn pledge to you: If you elect me your 44th president, thereby giving me the nickname \"44\" within the Bush clan, which would be\n\
  so cool, I will get Nick and Jessica to sing a duet at my inauguration. They owe me bigtime\x97I got them back together after  Newly Estranged .\n\
  Oh, my God, there's Majority Leader Bill Frist! Bill! Bill! Over here! Up on the podium! Bill, who are you wearing? What new pro-big-business and civil-liberties-curtailing initiatives do you have coming down the pipeline? Turn around, let's see the back! Are you and Hastert cooking up any slogans that convince the working class to vote against its own interests? Love ya! In a totally heterosexual way that promotes marriage between only a man and a woman, of course, as the 28th Amendment dictates, but that still recognizes our bond in Christian brotherhood! By invoking my total faith in and fealty to the 28th Amendment, my preceding comment about loving another man cannot be interpreted as sexually or romantically inclined in any way, and therefore I cannot be summarily detained or executed!\n\
  That's a wrap for tonight, Class II and III Vassals of Nebraska, but make sure you tune in for my first debate with my opponent tomorrow night\x97assuming he is not assassinated before then for some unknown reason by henchmen totally unconnected with me or my family\x97in the Independent Nation of FOX/Florida under the auspices of His Majesty Emperor Jeb! It's at 10/9 Central Bush Time, so you can still catch  CSI: Eugene  and  Ross ! I'm Billy Bush and I'm running for president\x97that still sounds weird to me, like it should be in a movie about a guy who's running for president! I wonder who'll play me in the movie version of my life after I heroically rise to the challenge presented by the terrible terrorist attacks by liberal Hollywood atheists that may or may not befall our country on July 29, 2009, or \"7/29,\" which will lead to martial law in Hollywood and the transfer of movie production to the government? Wait, that means I'd be in charge, so I could play myself! Then I could interview myself at the premiere! I'll leave you now with some subliminal mind-control messages playing under the new Jamie Lynn Spears campaign-exclusive hit song \"Flat Tax (featuring Lil Jon)\"!\n\
  - - - -"
date: 3/16/05
article_url: http://mcsweeneys.net/2005/3/16wayne.html
article_size: 5426
