--- 
lines: 
- BY  TODD ZUNIGA
- |
  

- Her middle name is Marie.
- |
  

- She is not one of 16,000 children&#151;there are far fewer than 16,000 kids in her family&#151;but still many by today's standard, though exactly how many, I cannot say.
- |
  

- She is the 3rd youngest.
- |
  

- One time, when her brother was dilly-dallying with a gun that shot darts, one got away and sunk into the young flesh of her ankle, not all the way, but enough to make a hole.
- |
  

- And after she started to cry, her brother asked her not to, and with pain stinging at her, a thousand bees a-buzzing, she stopped crying and clenched her teeth, fists, lips.
- |
  

- When she squeezes a big hunk of lime, more than your standard hunk of lime, into her Corona it sprays her with an unseen lilt.
- |
  

- It is my favorite part of the night, not because I particularly enjoy when people are sprayed with lime (though, apparently, I do), but because it makes me genuinely laugh.
- |
  

- She dabs a napkin against her face, instead of wiping with her hand.
- |
  

- She is old enough to drink, only a few months our waitress' elder.
- |
  

- She is empirically pretty.
- |
  

- She notices when men she goes on blind dates with have silver rings with the face of Elvis on them.
- |
  

- They have Hardcore Cider at the Bennigan's in Oak Brook, Illinois.
- |
  

- But not in a bottle.
- |
  

- Only on tap.
- |
  

- She is, surprisingly, not put off by my not ill-timed, but goofy, comment about sleeping with the waitress, whose name is Jenny.
- |
  

- Contrary to what Jenny comes to understand, Heather and I have not slept together, we do not regularly argue over trivialities, I am not worried that chicken fingers are going to make Heather fat, and we have not been together for seven months.
- |
  

- She does not care for honey-mustard sauce.
- |
  

- At 9:15 she has to go.
- |
  

- The scraping sound emanating from the front left wheel of my car is not going to go away unless I take it to a mechanic.
- |
  

- She used to bartend, which wiped out her entire Saturday.
- |
  

- But she quit, finally giving back her weekend.
- |
  

- She cares a great deal for the song that's playing softly above/around us.
- |
  

- Sting is singing it.
- |
  

- I talk too much.
- |
  

- And when I'm in the process of talking too much, I move my hands sporadically, as if an outraged Italian market-owner vehemently disagreeing with someone on an open Milan street about the price of cannoli.
- |
  

- She does not memorize movies.
- |
  

- And, in turn, does not remember the names of most actors.
- |
  

- It was I that brought up the topic of oral sex.
- |
  

- I tell her a stupid story indicating non-sympathetically&#151;putting the focus of the story at risk&#151;that my mother is in the hospital.
- |
  

- I had to include particular details to make sense of the previous eight sentences I had strung together, and that meant telling her where my mom was.
- |
  

- She talks semi-regularly to a man who works at Playboy Magazine, who used to be my boss, who taught me quite a bit about a lot of  things.
- |
  

- And not just how-to kinds of things, but sort of how to be a man in a way my father sometimes forgot, since I was the youngest of eight.
- |
  

- "Not to mention: he was a workaholic."
- |
  

- It is easy to like her.
- |
  

- Though, at this point, it is perfectly easy not to like-like her.
- |
  

- She took exactly 24 pictures while in New Orleans for six days.
- |
  

- Her boss is a man named Paul who looks like either Andre Dubus or Ernest Hemingway.
- |
  

- She cares physically for a male who lives in Denver whose hair reminds me of Vanilla Ice.
- |
  

- As does his face.
- |
  

- Andre Dubus looks like Ernest Hemingway.
- |
  

- "She has a thing for hotel bathrooms: the way they look, the amount of mirrors, the marble in the showers and tubs."
- |
  

- It is something we have in common.
- |
  

- She was engaged, some time ago, to a guy named something (what was his name?
- |
  

- Like he wasn't capable of ever making her really laugh.
- |
  

- Her car has a sunroof, and it's quite nice.
- |
  

- The car, not the sunroof.
- |
  

- Though the sunroof, too, is nice.
- |
  

- "My sunroof is my favorite part of my car, except for the fuzzy dice: a gift from the woman who sat behind me at Playboy Magazine when I worked for that man who taught me things about myself."
- |
  

- The dice are exceptional, though not really all that fuzzy.
- |
  

- "In the Bahamas she wore a white bikini, that she looked lovely in: that's the word I thought while sitting in her car before she went to pick up a friend at the airport, which she was going to be a couple minutes late for, regardless, which I took to be a positive sign: Lovely."
- |
  

- And in one picture she was posing as if she were a bodybuilder, hair like rainbow rays hovering, tucked behind small feminine ears.
- |
  

- I am happy she didn't marry that particular wrong guy.
- |
  

- "She is wearing new black shoes that draw my eyes to her ankle bones, which: and this is my first time for noticing an ankle in this way: appear like sweetly cut rubies under the dizzying new flesh of her leg."
- |
  

downcase_name: .......things.i.learned.o.ed.heather_by.todd.zunig
author: By Todd Zuniga
title: 32 1/2 Things I Learned on a Blind Date With a Pretty Girl Named Heather
text: |-
  BY  TODD ZUNIGA
  - - - -
  1. Her middle name is Marie.
  2. She is not one of 16,000 children&#151;there are far fewer than 16,000 kids in her
  family&#151;but still many by today's standard, though exactly how many, I cannot say.
  She is the 3rd youngest.
  3. One time, when her brother was dilly-dallying with a gun that shot
  darts, one got away and sunk into the young flesh of her ankle, not all the
  way, but enough to make a hole.  And after she started to cry, her brother
  asked her not to, and with pain stinging at her, a thousand bees a-buzzing,
  she stopped crying and clenched her teeth, fists, lips.
  4. When she squeezes a big hunk of lime, more than your standard hunk of
  lime, into her Corona it sprays her with an unseen lilt.  It is my
  favorite part of the night, not because I particularly enjoy when people
  are sprayed with lime (though, apparently, I do), but because it makes me
  genuinely laugh. She dabs a napkin against her face, instead of wiping with
  her hand.
  5. She is old enough to drink, only a few months our waitress' elder.
  6. She is empirically pretty.
  7. She notices when men she goes on blind dates with have silver rings with
  the face of Elvis on them.
  8. They have Hardcore Cider at the Bennigan's in Oak Brook, Illinois. But
  not in a bottle.  Only on tap.
  9. She is, surprisingly, not put off by my not ill-timed, but goofy,
  comment about sleeping with the waitress, whose name is Jenny.
  10. Contrary to what Jenny comes to understand, Heather and I have not
  slept together, we do not regularly argue over trivialities, I am not
  worried that chicken fingers are going to make Heather fat, and we have not
  been together for seven months.
  11. She does not care for honey-mustard sauce.
  12. At 9:15 she has to go.
  13. The scraping sound emanating from the front left wheel of my car is not
  going to go away unless I take it to a mechanic.
  14. She used to bartend, which wiped out her entire Saturday.  But she
  quit, finally giving back her weekend.
  15. She cares a great deal for the song that's playing softly above/around
  us.  Sting is singing it.
  16.  I talk too much.  And when I'm in the process of talking too much, I
  move my hands sporadically, as if an outraged Italian market-owner
  vehemently disagreeing with someone on an open Milan street about the price
  of cannoli.
  17. She does not memorize movies.  And, in turn, does not remember the
  names of most actors.
  18. It was I that brought up the topic of oral sex.
  19. I tell her a stupid story indicating non-sympathetically&#151;putting the
  focus of the story at risk&#151;that my mother is in the hospital. I had to
  include particular details to make sense of the previous eight sentences I
  had strung together, and that meant telling her where my mom was.
  20. She talks semi-regularly to a man who works at Playboy Magazine, who
  used to be my boss, who taught me quite a bit about a lot of  things.  And
  not just how-to kinds of things, but sort of how to be a man in a way my
  father sometimes forgot, since I was the youngest of eight.  Not to
  mention: he was a workaholic.
  21. It is easy to like her.  Though, at this point, it is perfectly easy
  not to like-like her.
  22. She took exactly 24 pictures while in New Orleans for six days.
  24. Her boss is a man named Paul who looks like either Andre Dubus or
  Ernest Hemingway.
  25. She cares physically for a male who lives in Denver whose hair reminds
  me of Vanilla Ice.  As does his face.
  26. Andre Dubus looks like Ernest Hemingway.
  27. She has a thing for hotel bathrooms: the way they look, the amount of
  mirrors, the marble in the showers and tubs.  It is something we have in
  common.
  28. She was engaged, some time ago, to a guy named something (what was his
  name?), who looked, in the pictures, completely wrong for her. Like he
  wasn't capable of ever making her really laugh.
  29. Her car has a sunroof, and it's quite nice. The car, not the sunroof.
  Though the sunroof, too, is nice.
  29 1/2. My sunroof is my favorite part of my car, except for the fuzzy
  dice: a gift from the woman who sat behind me at Playboy Magazine when I
  worked for that man who taught me things about myself.  The dice are
  exceptional, though not really all that fuzzy.
  30.  In the Bahamas she wore a white bikini, that she looked lovely in:
  that's the word I thought while sitting in her car before she went to pick
  up a friend at the airport, which she was going to be a couple minutes late
  for, regardless, which I took to be a positive sign: Lovely.  And in one
  picture she was posing as if she were a bodybuilder, hair like rainbow rays
  hovering, tucked behind small feminine ears.
  31. I am happy she didn't marry that particular wrong guy.
  32. She is wearing new black shoes that draw my eyes to her ankle bones,
  which: and this is my first time for noticing an ankle in this way: appear
  like sweetly cut rubies under the dizzying new flesh of her leg.
  &nbsp;
  &nbsp;
date: 04/04/01
article_url: http://mcsweeneys.net/2001/04/04blinddate.html
article_size: 4892
