--- 
lines: 
- BY  DAN KENNEDY
- |
  

- Kelly Jessing
- HYGIENIST
- I just remember thinking that there was no way this was happening.
- |
  

- It was just the three of us in Seattle, which at the time was the middle of nowhere.
- |
  

- We were basically laughing at the possibility of ever being huge.
- |
  

- I mean, in 1995 you would've been hard-pressed to find anyone who thought they needed a whiter smile.
- |
  

- And insurance plans didn't cover that sort of thing.
- |
  

- But then, almost overnight, we just kind of looked at each other and went, "Is this really happening?
- "\" Because suddenly, we were it."
- Allan Mesner, D.D.
- S.
- You couldn't have been bigger than our office in 1997.
- |
  

- Period.
- |
  

- And you like to say it's not going to change anything, but you have to imagine how it feels after years of people telling you that if you want to be big, you have to change your entire practice.
- |
  

- There's definitely a sense of "Fuck you, we didn't switch up anything.
- |
  

- We were doing this when hardly anyone wanted anything to do with it.
- |
  

- But we stayed true to who we are and now we're on top.
- "\" I mean, at the end of the day you can get a little high and mighty on the ."
- |
  

- Peter Richardson
- |
  

- MALE) RECEPTIONIST
- Well, we were told a million times that if you want to be a thriving practice, you had to focus on standard procedures .
- |
  

- Oh, and of course we were told for years that you couldn't be big with a male receptionist.
- |
  

- I meet dentists now that are like, "Yeah, we wanna get a male receptionist and go for the big time.
- "\" And I'm like, \""
- Oh, my God, it's come full circle.
- Tom Clark
- EDITOR,  COSMETIC DENTAL JOURNAL
- Nobody saw the Allan Mesner thing coming.
- |
  

- Nobody.
- |
  

- A small practice in Seattle, focusing largely on whitening.
- |
  

- They had a  guy  working the front desk.
- |
  

- I mean .
- |
  

- Laughs.
- |
  

- They flew me to Seattle in late 1996 with the hope that we'd run a story, and I got there and I could see what was going to happen.
- |
  

- You could see that within a matter of months, Mesner's office was never going to be the same.
- |
  

- And not just Mesner and his practice .
- |
  

- Basically, none of us would ever be the same.
- Allan Mesner, D.D.
- S.
- We were doing a trade show in Europe at one point and we couldn't get from the convention center to the van that was taking us back to the hotel.
- |
  

- That's how busy our booth was.
- |
  

- At one point the security guy looks at me and says, "We're gonna try taking you guys through 'em, and if we can't get through 'em, we're going to take you guys over the top of 'em.
- "\" And I actually thought, \""
- Well, yeah .
- |
  

- Kelly Jessing
- HYGIENIST
- For trade shows, we'd hook our receptionist, Peter, up with a walkie-talkie, send him out into the crowd in front of our booth, and tell him which people to give a pass to.
- |
  

- It would literally be like, "Guy, 6-foot-4, three back, four from the left, wearing a blue Ralph Lauren polo shirt.
- "\" And that guy would get the pass that says, \""
- Our hygienist, Kelly, would like to meet you after our presentation.
- "\" Or if it was for Allan, it would be like, \""
- Forty-something woman, front row, blond hair, with a blue blouse.
- "\" And she'd get the pass saying Dr. Mesner would like to meet her after the show."
- |
  

- You'd go back to the hotel, and there they'd be, in the lobby with passes, and it was like, "
- Ahhhh, I could get used to this.
- Allan Mesner, D.D.
- S.
- "If it hadn't blown up like this, I guess I'd still just be doing exactly what I always did: a minimally constructive cosmetic procedure ."
- |
  

- It's not like we planned any of this.
- |
  

- We were just doing what we wanted to do.
- Peter Richardson
- RECEPTIONIST
- I don't know what I'd be doing if things hadn't gotten so big.
- |
  

- I'm still not sure this is what I want to do for the rest of my life, even though we're huge now.
- |
  

- My biggest fantasy these days is just going back to being somebody who nobody knows .
- |
  

- I think I would've loved to be a cook in a diner somewhere.
- |
  

- "Or open a caf\xE9."
- Kelly Jessing
- HYGIENIST
- If this hadn't come along, I don't know.
- |
  

- I'd probably be in jail.
- |
  

- Long pause.
- |
  

- Or dead.
- |
  

- Dan Kennedy's
- Other Features .
- AN ORDER
- OF SERVICE
- FOR THE FIRST
- CONGREGATIONAL CHURCH OF
- CARL KASELL.
- BY  J. BYARD YODER
- |
  

- Introit
- All Things Considered  theme (arr.
- |
  

- Litany
- "LEADER: I'm Terry Gross."
- |
  

- From whence cometh our news?
- "CONGREGATION: Shallow, adversarial coverage holds sway, on broadcast as it is on cable."
- "LEADER: From whence cometh our commentary?"
- "CONGREGATION: Humorless, unreasoned opinions are a swelling tide all around us."
- "LEADER: Yet behold!"
- |
  

- A gust of  Fresh Air  for those living in the shadow of Fox.
- "CONGREGATION: What is this  Fresh Air ?"
- "LEADER: Our news cometh from Public Radio."
- "CONGREGATION: Thoughtful, in-depth reporting is the salvation of our days."
- "LEADER: Our commentary cometh from Public Radio."
- "CONGREGATION: Measured discussions of relevant issues make our minds easy."
- "LEADER AND CONGREGATION TOGETHER: Thanks be to listeners like you."
- Passing the Peace
- The congregation are invited to congratulate each other on their intelligence and good taste.
- Congregational Hymns
- G.
- |
  

- KEILLOR, SONG LEADER
- No. 142, "Tell Me Why"
- No. 576, Swedish folk song
- Communion
- All those attending are invited to participate.
- |
  

- Follow the usher's cue to walk up the aisle, accept a piece of bagel from the host, and dip it in the coffee in the mug with the  Morning Edition  logo on it.
- Reading of the Headlines
- L.
- |
  

- HANSEN
- "National:  President Bush Threatens Veto Over Iraq War Withdrawal Plans"
- "International:  Iranians Capture British Sailors in Disputed Waters"
- "Science:  Researchers Announce First Human-Sheep Hybrid"
- "Quirky:  Missoula Man Bicycles From Anchorage to Lima to Promote Alternative Fuels"
- Our Top Story
- S.
- |
  

- SIMON
- "\"Global Warming: Close to Home."
- "\" (Part three of a five-part series."
- |
  

- Hymn of Response
- I.
- |
  

- GLASS, SONG LEADER
- No. 337, "The Sun" (They Might Be Giants)
- Pledge Drive
- "Offertory:  Selections From the Peter, Paul, and Mary Reunion Tour ."
- |
  

- Available on CD as a thank-you gift for persons pledging $75 or more.
- |
  

- Please place your pledge cards in the tote bag as the ushers pass it down each row.
- |
  

- If you are already a member, consider increasing your membership level, or giving a gift membership to a friend or loved one.
- |
  

- The ushers will hand out thank-you gifts in the narthex after the service; all members receive a subscription to  Local Arts  magazine.
- Benediction
- "LEADERS: Behold, you've wasted another perfectly good hour."
- "CONGREGATION: Don't drive like my brother!"
- "LEADERS: Don't drive like my brother!"
- "CONGREGATION: Thanks be to NPR."
- Recessional
- "\"Little Deuce Coupe\""
- |
  

- Beach Boys)-->
- |
  

downcase_name: ......the.year.tooth.whit.ning.broke_by.dan.kenned
author: By Dan Kennedy
title: "1997: The Year Tooth Whitening Broke"
text: "BY  DAN KENNEDY\n\
  - - - -\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  I just remember thinking that there was no way this was happening. It was just the three of us in Seattle, which at the time was the middle of nowhere. We were basically laughing at the possibility of ever being huge. I mean, in 1995 you would've been hard-pressed to find anyone who thought they needed a whiter smile. And insurance plans didn't cover that sort of thing. But then, almost overnight, we just kind of looked at each other and went, \"Is this really happening?\" Because suddenly, we were it.\n\
  Allan Mesner, D.D.S.\n\
  You couldn't have been bigger than our office in 1997. Period. And you like to say it's not going to change anything, but you have to imagine how it feels after years of people telling you that if you want to be big, you have to change your entire practice. There's definitely a sense of \"Fuck you, we didn't switch up anything. We were doing this when hardly anyone wanted anything to do with it. But we stayed true to who we are and now we're on top.\" I mean, at the end of the day you can get a little high and mighty on the ... you know, the idea that you proved them all wrong.\n\
  Peter Richardson\n\
  (MALE) RECEPTIONIST\n\
  Well, we were told a million times that if you want to be a thriving practice, you had to focus on standard procedures ... play the game: crowns, fillings, molar preps and buildups, refer out a lot for your root canals and appendectomies and build alliances with other offices that way. Oh, and of course we were told for years that you couldn't be big with a male receptionist. I meet dentists now that are like, \"Yeah, we wanna get a male receptionist and go for the big time.\" And I'm like, \"Oh, my God, it's come full circle.\"\n\
  Tom Clark\n\
  EDITOR,  COSMETIC DENTAL JOURNAL\n\
  Nobody saw the Allan Mesner thing coming. Nobody. A small practice in Seattle, focusing largely on whitening. They had a  guy  working the front desk. I mean ... ( Laughs. ) They flew me to Seattle in late 1996 with the hope that we'd run a story, and I got there and I could see what was going to happen. You could see that within a matter of months, Mesner's office was never going to be the same. And not just Mesner and his practice ... Basically, none of us would ever be the same.\n\
  Allan Mesner, D.D.S.\n\
  We were doing a trade show in Europe at one point and we couldn't get from the convention center to the van that was taking us back to the hotel. That's how busy our booth was. At one point the security guy looks at me and says, \"We're gonna try taking you guys through 'em, and if we can't get through 'em, we're going to take you guys over the top of 'em.\" And I actually thought, \"Well, yeah ... that's a pretty good idea.\"\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  For trade shows, we'd hook our receptionist, Peter, up with a walkie-talkie, send him out into the crowd in front of our booth, and tell him which people to give a pass to. It would literally be like, \"Guy, 6-foot-4, three back, four from the left, wearing a blue Ralph Lauren polo shirt.\" And that guy would get the pass that says, \"Our hygienist, Kelly, would like to meet you after our presentation.\" Or if it was for Allan, it would be like, \"Forty-something woman, front row, blond hair, with a blue blouse.\" And she'd get the pass saying Dr. Mesner would like to meet her after the show. You'd go back to the hotel, and there they'd be, in the lobby with passes, and it was like, \"Ahhhh, I could get used to this.\"\n\
  Allan Mesner, D.D.S.\n\
  If it hadn't blown up like this, I guess I'd still just be doing exactly what I always did: a minimally constructive cosmetic procedure ... whitening. It's not like we planned any of this. We were just doing what we wanted to do.\n\
  Peter Richardson\n\
  RECEPTIONIST\n\
  I don't know what I'd be doing if things hadn't gotten so big. I'm still not sure this is what I want to do for the rest of my life, even though we're huge now. My biggest fantasy these days is just going back to being somebody who nobody knows ... I think I would've loved to be a cook in a diner somewhere. Or open a caf\xE9.\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  If this hadn't come along, I don't know. I'd probably be in jail. ( Long pause. ) Or dead.\n\
  - - - -\n\
  Dan Kennedy's\n\
  Other Features .\n\
  AN ORDER\n\
  OF SERVICE\n\
  FOR THE FIRST\n\
  CONGREGATIONAL CHURCH OF\n\
  CARL KASELL.\n\
  BY  J. BYARD YODER\n\
  - - - -\n\
  Introit\n\
  All Things Considered  theme (arr. for organ)\n\
  Litany\n\
  LEADER: I'm Terry Gross. From whence cometh our news?\n\
  CONGREGATION: Shallow, adversarial coverage holds sway, on broadcast as it is on cable.\n\
  LEADER: From whence cometh our commentary?\n\
  CONGREGATION: Humorless, unreasoned opinions are a swelling tide all around us.\n\
  LEADER: Yet behold! A gust of  Fresh Air  for those living in the shadow of Fox.\n\
  CONGREGATION: What is this  Fresh Air ?\n\
  LEADER: Our news cometh from Public Radio.\n\
  CONGREGATION: Thoughtful, in-depth reporting is the salvation of our days.\n\
  LEADER: Our commentary cometh from Public Radio.\n\
  CONGREGATION: Measured discussions of relevant issues make our minds easy.\n\
  LEADER AND CONGREGATION TOGETHER: Thanks be to listeners like you.\n\
  Passing the Peace\n\
  The congregation are invited to congratulate each other on their intelligence and good taste.\n\
  Congregational Hymns\n\
  G. KEILLOR, SONG LEADER\n\
  No. 142, \"Tell Me Why\"\n\
  No. 576, Swedish folk song\n\
  Communion\n\
  All those attending are invited to participate. Follow the usher's cue to walk up the aisle, accept a piece of bagel from the host, and dip it in the coffee in the mug with the  Morning Edition  logo on it.\n\
  Reading of the Headlines\n\
  L. HANSEN\n\
  National:  President Bush Threatens Veto Over Iraq War Withdrawal Plans\n\
  International:  Iranians Capture British Sailors in Disputed Waters\n\
  Science:  Researchers Announce First Human-Sheep Hybrid\n\
  Quirky:  Missoula Man Bicycles From Anchorage to Lima to Promote Alternative Fuels\n\
  Our Top Story\n\
  S. SIMON\n\
  \"Global Warming: Close to Home.\" (Part three of a five-part series.)\n\
  Hymn of Response\n\
  I. GLASS, SONG LEADER\n\
  No. 337, \"The Sun\" (They Might Be Giants)\n\
  Pledge Drive\n\
  Offertory:  Selections From the Peter, Paul, and Mary Reunion Tour . (Available on CD as a thank-you gift for persons pledging $75 or more.)\n\
  Please place your pledge cards in the tote bag as the ushers pass it down each row. If you are already a member, consider increasing your membership level, or giving a gift membership to a friend or loved one. The ushers will hand out thank-you gifts in the narthex after the service; all members receive a subscription to  Local Arts  magazine.\n\
  Benediction\n\
  LEADERS: Behold, you've wasted another perfectly good hour.\n\
  CONGREGATION: Don't drive like my brother!\n\
  LEADERS: Don't drive like my brother!\n\
  CONGREGATION: Thanks be to NPR.\n\
  Recessional\n\
  \"Little Deuce Coupe\" (Beach Boys)-->\n\
  - - - -"
date: 5/4/07
article_url: http://mcsweeneys.net/2007/5/4yoder.html
article_size: 6716
