--- 
lines: 
- BY  MATTHEW BALDWIN
- |
  

- Proposition 7
- "Yes:  This is the kind of initiative that elections are all about, a chance for the citizens to send a message to Washington."
- |
  

- "When we talk of \"sending a message,\" we are usually speaking figuratively, urging you to vote so as to indirectly express satisfaction in or disapproval of certain politicians or policies, but the beauty of Proposition 7 is that it sends a literal message: if passed, an actual, handwritten note card reading \"You suck\" will be sent to each and every representative and senator at both the state and federal level."
- |
  

- Yes, the cost of decorative stationery will certainly exacerbate our budget woes, but how often do you get the opportunity to truly have your voice heard?
- |
  

- Vote "Yes" on Proposition 7.
- Proposition 19
- "Yes:  If Proposition 19 passes, every citizen who votes in this midterm election will receive a brand-new Nintendo Wii game console, to be funded by a special tax levied upon those citizens who did not vote."
- |
  

- We not only applaud this as the greatest "get out the vote" tactic of all time but we also really want a Nintendo Wii. Vote "Yes" on Proposition 19.
- Congressional District No. 8 Representative
- "Jennifer Salt (Republican):  Salt ran the most negative campaign in the nation, heaping slanderous recriminations upon her opponent, Jonathan Snite, with an intensity we have not seen in our 37 years of political coverage."
- |
  

- Nor, in that time, have we seen such a cavalier disregard for the truth.
- |
  

- Her allegations of murder were shown to be groundless, she never produced the "conclusive proof" of Snite's supposed connections to Al Qaeda, and her unrelenting attempts to portray her opponent as a hedonistic troglodyte contradicted the testimony of his friends and family, who lauded his exemplary ethics and leadership as a minister, Eagle Scout, and outstanding citizen. Snite's name is now synonymous with the most scandalous smear campaign we've ever had the misfortune to see, and he serves as a perpetual reminder of our disgust for contemporary politics. The sooner he disappears from the limelight, the better we'll feel. Vote Jennifer Salt for Congressional District No. 8 Representative.
- Legislative District No. 43 Senator
- "Martin Fow (Unaffiliated):  Many candidates claim to be \"outsiders,\" but Martin Fow is the real deal. When we contacted him yesterday afternoon, he was unable to name two of the three branches of government, thought Vince Vaughn was the current vice president, and was unaware that he was a candidate for this position. His opponent, meanwhile, is an accomplished legislator with years of experience and accumulated wisdom\x97just the kind of fat-cat Beltway insider that needs to be shown the door! Vote Martin Fow for Legislative District No. 43 Senator."
- Metropolitan County Council District No. 11
- "Bart Brady (Conspiratarian):  When he's not making balloon animals at the local park, Brady promulgates an astoundingly diverse collection of conspiracy theories on his website theycontroleverything."
- |
  

- No other candidate is asking the hard questions, like "Did geophysicists assassinate Jim Henson?
- "\" or \""
- Why is there hydrogen in America's water supply?
- "\" His unique perspective on world affairs and his ability to think not only outside the box but outside all known geometric constructs make him perfectly suited for this position."
- |
  

- And he's running unopposed.
- |
  

- Vote Bart Brady for Metropolitan County Council District No. 11.
- State Supreme Court Position No. 3
- "Ben Dover (Nonpartisan):  If you don't see him on the ballot, loudly ask to vote for him by name."
- |
  

downcase_name: .....voter.s.guide_by.matthew.baldwin
author: By Matthew Baldwin
title: 2006 Voter's Guide
text: "BY  MATTHEW BALDWIN\n\
  - - - -\n\
  Proposition 7\n\
  Yes:  This is the kind of initiative that elections are all about, a chance for the citizens to send a message to Washington. When we talk of \"sending a message,\" we are usually speaking figuratively, urging you to vote so as to indirectly express satisfaction in or disapproval of certain politicians or policies, but the beauty of Proposition 7 is that it sends a literal message: if passed, an actual, handwritten note card reading \"You suck\" will be sent to each and every representative and senator at both the state and federal level. Yes, the cost of decorative stationery will certainly exacerbate our budget woes, but how often do you get the opportunity to truly have your voice heard? Vote \"Yes\" on Proposition 7.\n\
  Proposition 19\n\
  Yes:  If Proposition 19 passes, every citizen who votes in this midterm election will receive a brand-new Nintendo Wii game console, to be funded by a special tax levied upon those citizens who did not vote. We not only applaud this as the greatest \"get out the vote\" tactic of all time but we also really want a Nintendo Wii. Vote \"Yes\" on Proposition 19.\n\
  Congressional District No. 8 Representative\n\
  Jennifer Salt (Republican):  Salt ran the most negative campaign in the nation, heaping slanderous recriminations upon her opponent, Jonathan Snite, with an intensity we have not seen in our 37 years of political coverage. Nor, in that time, have we seen such a cavalier disregard for the truth. Her allegations of murder were shown to be groundless, she never produced the \"conclusive proof\" of Snite's supposed connections to Al Qaeda, and her unrelenting attempts to portray her opponent as a hedonistic troglodyte contradicted the testimony of his friends and family, who lauded his exemplary ethics and leadership as a minister, Eagle Scout, and outstanding citizen. Snite's name is now synonymous with the most scandalous smear campaign we've ever had the misfortune to see, and he serves as a perpetual reminder of our disgust for contemporary politics. The sooner he disappears from the limelight, the better we'll feel. Vote Jennifer Salt for Congressional District No. 8 Representative.\n\
  Legislative District No. 43 Senator\n\
  Martin Fow (Unaffiliated):  Many candidates claim to be \"outsiders,\" but Martin Fow is the real deal. When we contacted him yesterday afternoon, he was unable to name two of the three branches of government, thought Vince Vaughn was the current vice president, and was unaware that he was a candidate for this position. His opponent, meanwhile, is an accomplished legislator with years of experience and accumulated wisdom\x97just the kind of fat-cat Beltway insider that needs to be shown the door! Vote Martin Fow for Legislative District No. 43 Senator.\n\
  Metropolitan County Council District No. 11\n\
  Bart Brady (Conspiratarian):  When he's not making balloon animals at the local park, Brady promulgates an astoundingly diverse collection of conspiracy theories on his website theycontroleverything.com. No other candidate is asking the hard questions, like \"Did geophysicists assassinate Jim Henson?\" or \"Why is there hydrogen in America's water supply?\" His unique perspective on world affairs and his ability to think not only outside the box but outside all known geometric constructs make him perfectly suited for this position. And he's running unopposed. Vote Bart Brady for Metropolitan County Council District No. 11.\n\
  State Supreme Court Position No. 3\n\
  Ben Dover (Nonpartisan):  If you don't see him on the ballot, loudly ask to vote for him by name.\n\
  - - - -"
date: 11/7/06
article_url: http://mcsweeneys.net/2006/11/7baldwin.html
article_size: 3581
