--- 
lines: 
- BY  DAN KENNEDY
- |
  

- Kelly Jessing
- HYGIENIST
- I just remember thinking that there was no way this was happening.
- |
  

- It was just the three of us in Seattle, which at the time was the middle of nowhere.
- |
  

- We were basically laughing at the possibility of ever being huge.
- |
  

- I mean, in 1995 you would've been hard-pressed to find anyone who thought they needed a whiter smile.
- |
  

- And insurance plans didn't cover that sort of thing.
- |
  

- But then, almost overnight, we just kind of looked at each other and went, "Is this really happening?
- "\" Because suddenly, we were it."
- Allan Mesner, D.D.
- S.
- You couldn't have been bigger than our office in 1997.
- |
  

- Period.
- |
  

- And you like to say it's not going to change anything, but you have to imagine how it feels after years of people telling you that if you want to be big, you have to change your entire practice.
- |
  

- There's definitely a sense of "Fuck you, we didn't switch up anything.
- |
  

- We were doing this when hardly anyone wanted anything to do with it.
- |
  

- But we stayed true to who we are and now we're on top.
- "\" I mean, at the end of the day you can get a little high and mighty on the ."
- |
  

- Peter Richardson
- |
  

- MALE) RECEPTIONIST
- Well, we were told a million times that if you want to be a thriving practice, you had to focus on standard procedures .
- |
  

- Oh, and of course we were told for years that you couldn't be big with a male receptionist.
- |
  

- I meet dentists now that are like, "Yeah, we wanna get a male receptionist and go for the big time.
- "\" And I'm like, \""
- Oh, my God, it's come full circle.
- Tom Clark
- EDITOR,  COSMETIC DENTAL JOURNAL
- Nobody saw the Allan Mesner thing coming.
- |
  

- Nobody.
- |
  

- A small practice in Seattle, focusing largely on whitening.
- |
  

- They had a  guy  working the front desk.
- |
  

- I mean .
- |
  

- Laughs.
- |
  

- They flew me to Seattle in late 1996 with the hope that we'd run a story, and I got there and I could see what was going to happen.
- |
  

- You could see that within a matter of months, Mesner's office was never going to be the same.
- |
  

- And not just Mesner and his practice .
- |
  

- Basically, none of us would ever be the same.
- Allan Mesner, D.D.
- S.
- We were doing a trade show in Europe at one point and we couldn't get from the convention center to the van that was taking us back to the hotel.
- |
  

- That's how busy our booth was.
- |
  

- At one point the security guy looks at me and says, "We're gonna try taking you guys through 'em, and if we can't get through 'em, we're going to take you guys over the top of 'em.
- "\" And I actually thought, \""
- Well, yeah .
- |
  

- Kelly Jessing
- HYGIENIST
- For trade shows, we'd hook our receptionist, Peter, up with a walkie-talkie, send him out into the crowd in front of our booth, and tell him which people to give a pass to.
- |
  

- It would literally be like, "Guy, 6-foot-4, three back, four from the left, wearing a blue Ralph Lauren polo shirt.
- "\" And that guy would get the pass that says, \""
- Our hygienist, Kelly, would like to meet you after our presentation.
- "\" Or if it was for Allan, it would be like, \""
- Forty-something woman, front row, blond hair, with a blue blouse.
- "\" And she'd get the pass saying Dr. Mesner would like to meet her after the show."
- |
  

- You'd go back to the hotel, and there they'd be, in the lobby with passes, and it was like, "
- Ahhhh, I could get used to this.
- Allan Mesner, D.D.
- S.
- "If it hadn't blown up like this, I guess I'd still just be doing exactly what I always did: a minimally constructive cosmetic procedure ."
- |
  

- It's not like we planned any of this.
- |
  

- We were just doing what we wanted to do.
- Peter Richardson
- RECEPTIONIST
- I don't know what I'd be doing if things hadn't gotten so big.
- |
  

- I'm still not sure this is what I want to do for the rest of my life, even though we're huge now.
- |
  

- My biggest fantasy these days is just going back to being somebody who nobody knows .
- |
  

- I think I would've loved to be a cook in a diner somewhere.
- |
  

- "Or open a caf\xE9."
- Kelly Jessing
- HYGIENIST
- If this hadn't come along, I don't know.
- |
  

- I'd probably be in jail.
- |
  

- Long pause.
- |
  

- Or dead.
- |
  

downcase_name: ......the.year.tooth.whit.ning.broke_by.dan.kenne1
author: By Dan Kennedy
title: "1997: The Year Tooth Whitening Broke"
text: "BY  DAN KENNEDY\n\
  - - - -\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  I just remember thinking that there was no way this was happening. It was just the three of us in Seattle, which at the time was the middle of nowhere. We were basically laughing at the possibility of ever being huge. I mean, in 1995 you would've been hard-pressed to find anyone who thought they needed a whiter smile. And insurance plans didn't cover that sort of thing. But then, almost overnight, we just kind of looked at each other and went, \"Is this really happening?\" Because suddenly, we were it.\n\
  Allan Mesner, D.D.S.\n\
  You couldn't have been bigger than our office in 1997. Period. And you like to say it's not going to change anything, but you have to imagine how it feels after years of people telling you that if you want to be big, you have to change your entire practice. There's definitely a sense of \"Fuck you, we didn't switch up anything. We were doing this when hardly anyone wanted anything to do with it. But we stayed true to who we are and now we're on top.\" I mean, at the end of the day you can get a little high and mighty on the ... you know, the idea that you proved them all wrong.\n\
  Peter Richardson\n\
  (MALE) RECEPTIONIST\n\
  Well, we were told a million times that if you want to be a thriving practice, you had to focus on standard procedures ... play the game: crowns, fillings, molar preps and buildups, refer out a lot for your root canals and appendectomies and build alliances with other offices that way. Oh, and of course we were told for years that you couldn't be big with a male receptionist. I meet dentists now that are like, \"Yeah, we wanna get a male receptionist and go for the big time.\" And I'm like, \"Oh, my God, it's come full circle.\"\n\
  Tom Clark\n\
  EDITOR,  COSMETIC DENTAL JOURNAL\n\
  Nobody saw the Allan Mesner thing coming. Nobody. A small practice in Seattle, focusing largely on whitening. They had a  guy  working the front desk. I mean ... ( Laughs. ) They flew me to Seattle in late 1996 with the hope that we'd run a story, and I got there and I could see what was going to happen. You could see that within a matter of months, Mesner's office was never going to be the same. And not just Mesner and his practice ... Basically, none of us would ever be the same.\n\
  Allan Mesner, D.D.S.\n\
  We were doing a trade show in Europe at one point and we couldn't get from the convention center to the van that was taking us back to the hotel. That's how busy our booth was. At one point the security guy looks at me and says, \"We're gonna try taking you guys through 'em, and if we can't get through 'em, we're going to take you guys over the top of 'em.\" And I actually thought, \"Well, yeah ... that's a pretty good idea.\"\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  For trade shows, we'd hook our receptionist, Peter, up with a walkie-talkie, send him out into the crowd in front of our booth, and tell him which people to give a pass to. It would literally be like, \"Guy, 6-foot-4, three back, four from the left, wearing a blue Ralph Lauren polo shirt.\" And that guy would get the pass that says, \"Our hygienist, Kelly, would like to meet you after our presentation.\" Or if it was for Allan, it would be like, \"Forty-something woman, front row, blond hair, with a blue blouse.\" And she'd get the pass saying Dr. Mesner would like to meet her after the show. You'd go back to the hotel, and there they'd be, in the lobby with passes, and it was like, \"Ahhhh, I could get used to this.\"\n\
  Allan Mesner, D.D.S.\n\
  If it hadn't blown up like this, I guess I'd still just be doing exactly what I always did: a minimally constructive cosmetic procedure ... whitening. It's not like we planned any of this. We were just doing what we wanted to do.\n\
  Peter Richardson\n\
  RECEPTIONIST\n\
  I don't know what I'd be doing if things hadn't gotten so big. I'm still not sure this is what I want to do for the rest of my life, even though we're huge now. My biggest fantasy these days is just going back to being somebody who nobody knows ... I think I would've loved to be a cook in a diner somewhere. Or open a caf\xE9.\n\
  Kelly Jessing\n\
  HYGIENIST\n\
  If this hadn't come along, I don't know. I'd probably be in jail. ( Long pause. ) Or dead.\n\
  - - - -"
date: 2/3/06
article_url: http://mcsweeneys.net/2006/2/3kennedy.html
article_size: 4177
