--- 
lines: 
- BY  PAUL HELTZEL  AND  MARK RICHARDSON
- |
  

- The Cocktail Hour
- We look through an enormous studio window into the living room of TODD ANDERSON.
- |
  

- TODD drinks from a levitating martini glass with two olives.
- |
  

- The olives each have dense, Saturn-like rings of pimento.
- |
  

- A slight electronic chorus sounds, alerting TODD to the arrival of a new message.
- |
  

- He toggles the switch on his jetpack, then navigates the living room, over the bar area, skirting the top of the ottoman, and lands neatly by a large, brown appliance with the words  Mailinator  spelled out in chrome.
- TODD
- Now what could this be?
- TODD pushes a small T-shaped lever, and a football-sized plastic container appears.
- |
  

- "He opens the container and pulls out a blue note, which reads:   I'm downstairs."
- TODD
- This could be trouble.
- TODD pulls what appears to be a rounded gun, then quickly fires two shots.
- |
  

- One sends a small plunger near the front entrance.
- |
  

- The plunger gently depresses a button, opening the main door with a whisper.
- |
  

- The second shot sends a shattering concussive blast, which opens the screen door.
- SARAH enters the door on a Ginger, a scooter-like craft with incredible stability.
- |
  

- She rolls through the front door, over the couch, and stops a millimeter away from TODD's face.
- SARAH
- A little early for a drink, no?
- TODD
- It's six-thirty somewhere.
- He takes one last sip of his drink, then throws the martini glass.
- |
  

- As it speeds across the room, an invisible charge in the stem detonates, pulverizing it.
- |
  

- The ashes fall harmlessly into the fireplace.
- SARAH pulls out a remote which sends a powerful focused sonic wave in the direction of TODD's cheek.
- |
  

- It has the effect of slapping him, but it also rips open his shirt, and gives a wind-blown look to his hair.
- SARAH
- I think you know what that's for.
- TODD rushes to SARAH, kisses her with his mouth open wide, and turns his ring twice, setting off a wireless signal to bring up mood music and dim the lights.
- SARAH
- Filthy savage.
- TODD
- But I never touched her.
- SARAH
- Then whose baby is Antonio?
- TODD
- The golf pro's.
- SARAH
- Todd, I&nbsp;&#151;&nbsp;
- TODD
- Don't say it.
- |
  

- You don't have to.
- "They both put their hands into a tube, and remove them to show smoldering new tattoos, which read:"
- TODD & SARAH&nbsp;&#151;&nbsp;BACK 'N BUSINESS
- FADE TO BLACK.
- |
  

- Father Of The Year
- We open on a shot of RAY WORTHY sitting on a La-Z-Boy in front of the television.
- |
  

- He is about thirty-seven, unshaven, with a dirty t-shirt and a large salad bowl of cocktail wieners in his lap.
- |
  

- In his other hand is a can of Braumeister.
- |
  

- He stares intently at the television as his 8-year old son walks into the room behind him.
- SON
- Dad, I got in a fight with Justin today.
- RAY says nothing, keeping his eyes trained on the TV.
- SON
- He said that his dad called you a lazy idiot.
- |
  

- I told him you were the smartest dad in the world.
- RAY takes a slug from his beer.
- SON
- Are you the smartest dad in the world, Dad?
- RAY jams a handful of cocktail wieners in his mouth, chews, swallows, and wipes his chin with a terry-cloth wristband.
- RAY
- Fuckin' A.
- THE END
- |
  

downcase_name: ...second.theater.proudly.ltzel.and.mark.richardso
author: By Paul Heltzel and Mark Richardson
title: 15 Second Theater Proudly Presents "The Cocktail Hour" and "Father of the Year"
text: |-
  BY  PAUL HELTZEL  AND  MARK RICHARDSON
  - - - -
  The Cocktail Hour
  We look through an enormous studio window into the living room of TODD ANDERSON. TODD drinks from a levitating martini glass with two olives. The olives each have dense, Saturn-like rings of pimento. A slight electronic chorus sounds, alerting TODD to the arrival of a new message. He toggles the switch on his jetpack, then navigates the living room, over the bar area, skirting the top of the ottoman, and lands neatly by a large, brown appliance with the words  Mailinator  spelled out in chrome.
  TODD
  Now what could this be?
  TODD pushes a small T-shaped lever, and a football-sized plastic container appears. He opens the container and pulls out a blue note, which reads:
  
   I'm downstairs.
  TODD
  This could be trouble.
  TODD pulls what appears to be a rounded gun, then quickly fires two shots. One sends a small plunger near the front entrance. The plunger gently depresses a button, opening the main door with a whisper. The second shot sends a shattering concussive blast, which opens the screen door.
  SARAH enters the door on a Ginger, a scooter-like craft with incredible stability. She rolls through the front door, over the couch, and stops a millimeter away from TODD's face.
  SARAH
  A little early for a drink, no?
  TODD
  It's six-thirty somewhere.
  He takes one last sip of his drink, then throws the martini glass. As it speeds across the room, an invisible charge in the stem detonates, pulverizing it. The ashes fall harmlessly into the fireplace.
  SARAH pulls out a remote which sends a powerful focused sonic wave in the direction of TODD's cheek. It has the effect of slapping him, but it also rips open his shirt, and gives a wind-blown look to his hair.
  SARAH
  I think you know what that's for.
  TODD rushes to SARAH, kisses her with his mouth open wide, and turns his ring twice, setting off a wireless signal to bring up mood music and dim the lights.
  SARAH
  Filthy savage.
  TODD
  But I never touched her.
  SARAH
  Then whose baby is Antonio?
  TODD
  The golf pro's.
  SARAH
  Todd, I&nbsp;&#151;&nbsp;
  TODD
  Don't say it. You don't have to.
  They both put their hands into a tube, and remove them to show smoldering new tattoos, which read:
  TODD & SARAH&nbsp;&#151;&nbsp;BACK 'N BUSINESS
  FADE TO BLACK.
  - - - -
  Father Of The Year
  We open on a shot of RAY WORTHY sitting on a La-Z-Boy in front of the television. He is about thirty-seven, unshaven, with a dirty t-shirt and a large salad bowl of cocktail wieners in his lap. In his other hand is a can of Braumeister. He stares intently at the television as his 8-year old son walks into the room behind him.
  SON
  Dad, I got in a fight with Justin today.
  RAY says nothing, keeping his eyes trained on the TV.
  SON
  He said that his dad called you a lazy idiot. I told him you were the smartest dad in the world.
  RAY takes a slug from his beer.
  SON
  Are you the smartest dad in the world, Dad?
  RAY jams a handful of cocktail wieners in his mouth, chews, swallows, and wipes his chin with a terry-cloth wristband.
  RAY
  Fuckin' A.
  THE END
  &nbsp;
  &nbsp;
date: 08/16/01
article_url: http://mcsweeneys.net/2001/08/16theater.html
article_size: 3058
