--- 
lines: 
- BY EVANY THOMAS
- |
  

- Lords of the New Church Fear Afterlife
- Starship Sparks Crowded House
- "Chicago, Boston, Berlin, Asia: Damned"
- The Waitresses Squeeze the Specials
- Pet Shop Boys Fixx Stray Cats, Toto
- Flock of Seagulls Jam the Tubes
- Sisters of Mercy Cure Television
- Scorpions Sting Tracey Ullman
- Police Poison Loverboy Cult
- The English Beat New Kids on the Block
- Scandal, Madness, Germs
- Yes, the Smiths Heart Everything But the Girl
- Gene Loves Jezebel
- |
  

downcase_name: ...s.lineups.that.read.li.headlines_by.evany.thoma
author: By Evany Thomas
title: "'80s Lineups That Read Like Tabloid Headlines"
text: |-
  BY EVANY THOMAS
  - - - -
  Lords of the New Church Fear Afterlife
  Starship Sparks Crowded House
  Chicago, Boston, Berlin, Asia: Damned
  The Waitresses Squeeze the Specials
  Pet Shop Boys Fixx Stray Cats, Toto
  Flock of Seagulls Jam the Tubes
  Sisters of Mercy Cure Television
  Scorpions Sting Tracey Ullman
  Police Poison Loverboy Cult
  The English Beat New Kids on the Block
  Scandal, Madness, Germs
  Yes, the Smiths Heart Everything But the Girl
  Gene Loves Jezebel
  - - - -
date: 4/5/05
article_url: http://mcsweeneys.net/2005/4/5thomas.html
article_size: 461
