--- 
lines: 
- BY  LEE TYLER
- |
  

- It totally goes without saying, but he just doesn't seem to understand that the apartment is maddeningly messy!
- |
  

- Put the boxers in the laundry hamper where they belong, or you'd better hit the road, Jack!
- |
  

- You just can't figure out what kind of thoughts are percolating through that brilliant brain, but whatever they are, your birthday should be somewhere among them!
- |
  

- What's with his suspiciously effeminate friend always calling your cell phone, breathing heavily, and then hastily hanging up?
- |
  

- Duh, you totally have caller ID, and the joke wasn't even funny the first three hundred and eighty-seven times.
- |
  

- And the four hundred and twenty-two text messages weren't even jokes!
- |
  

- We love it when he totally takes time to introduce you to the people he cares for most, but not when he consistently introduces you as, "The Whore of Babylon, prophesied destroyer of my world.
- |
  

- He doesn't like it when you redecorate too much, but is it really too much to ask him to take down those dreadful mounted cat heads from his glory days of bachelorhood?
- |
  

- After all, why does a married man need all those severed heads when he has you?
- |
  

- When you gaze into his eyes, his muscles tauten, and he screams, "Don't fucking look at me!
- |
  

- Don't you fucking look at me!
- "\" Is it really so hard for him to sit tight while you peer into the windows of his dark and stormy soul?"
- |
  

- What's with him never returning your calls or e-mails?
- |
  

- And when you do sneak past the security guards and pesky co-workers, what's with him always looking around nervously and yelping, "Leave me alone!
- "\"?"
- |
  

- If he doesn't shape up, you'd better ship him out!
- |
  

- You'd think your guy would have figured out how to put the toilet seat back in its proper place by now&#8212;it's not like you moved in yesterday!
- |
  

- Maybe they do things differently in Rhode Island, but here in civilization the toilet seat does not "belong in the land fill!
- |
  

- How come every time you suggest a movie you want to see, he laughs light-heartedly, rubs his palms together, and throws you and all your belonging out onto the street?
- |
  

- Time to trade him in for a new model, the kind that likes crying with you over a bucket of lightly buttered popcorn at a Meg Ryan flick.
- |
  

- When you first met he promised he wouldn't kick tramps anymore, but on the weekends he still goes out with his friends, he still drinks more Silver Bullets than he can count, and he still gets off booting sleeping tramps.
- |
  

- Time for him to consider your feelings for a change, or you're gonna hafta kick him to the curb, girlfriend.
- |
  

downcase_name: ...signs.your.guy.s.gotta.go_by.lee.tyler
author: By Lee Tyler
title: 10 Signs Your Guy's Gotta Go
text: |-
  BY  LEE TYLER
  - - - -
  1. It totally goes without saying, but he just doesn't seem to understand that the apartment is maddeningly messy! Put the boxers in the laundry hamper where they belong, or you'd better hit the road, Jack!
  2. You just can't figure out what kind of thoughts are percolating through that brilliant brain, but whatever they are, your birthday should be somewhere among them!
  3. What's with his suspiciously effeminate friend always calling your cell phone, breathing heavily, and then hastily hanging up? Duh, you totally have caller ID, and the joke wasn't even funny the first three hundred and eighty-seven times. And the four hundred and twenty-two text messages weren't even jokes!
  4. We love it when he totally takes time to introduce you to the people he cares for most, but not when he consistently introduces you as, "The Whore of Babylon, prophesied destroyer of my world."
  5. He doesn't like it when you redecorate too much, but is it really too much to ask him to take down those dreadful mounted cat heads from his glory days of bachelorhood? After all, why does a married man need all those severed heads when he has you?
  6. When you gaze into his eyes, his muscles tauten, and he screams, "Don't fucking look at me! Don't you fucking look at me!" Is it really so hard for him to sit tight while you peer into the windows of his dark and stormy soul?
  7. What's with him never returning your calls or e-mails? And when you do sneak past the security guards and pesky co-workers, what's with him always looking around nervously and yelping, "Leave me alone!"? If he doesn't shape up, you'd better ship him out!
  8. You'd think your guy would have figured out how to put the toilet seat back in its proper place by now&#8212;it's not like you moved in yesterday! Maybe they do things differently in Rhode Island, but here in civilization the toilet seat does not "belong in the land fill!"
  9. How come every time you suggest a movie you want to see, he laughs light-heartedly, rubs his palms together, and throws you and all your belonging out onto the street? Time to trade him in for a new model, the kind that likes crying with you over a bucket of lightly buttered popcorn at a Meg Ryan flick.
  10. When you first met he promised he wouldn't kick tramps anymore, but on the weekends he still goes out with his friends, he still drinks more Silver Bullets than he can count, and he still gets off booting sleeping tramps. Time for him to consider your feelings for a change, or you're gonna hafta kick him to the curb, girlfriend.
  &nbsp;
  &nbsp;
date: 10/06/03
article_url: http://mcsweeneys.net/2003/10/06signs.html
article_size: 2576
