--- 
lines: 
- BY  JACK RUENPRAPAN
- |
  

- I don't have a lot of time to explain right now, but you're going to have to trust me.
- During my years of covert government service, I have gone through hell and back.
- |
  

- Yes, I am proud to have served my country, helping to avoid many horrific tragedies.
- |
  

- Rules are meant to be followed, but I have a history of insubordination.
- |
  

- "While the methods I employ may seem harsh, I always have one goal in mind: saving lives."
- |
  

- In the process, I have had to make some tough decisions, often within seconds, in order to avert disaster.
- "To my friends: I'm sorry for not telling you everything."
- |
  

- It's not that I don't trust you, but we are operating on a strict need-to-know basis.
- |
  

- But when I'm in a jam, I hope I can count on you.
- |
  

- Whether it's illegally hacking passwords of suspected terrorist financiers or keeping your mouth shut about my smack habit, I really appreciate everything.
- |
  

- And if you ever find yourself unavoidably chained to a weapon of mass destruction counting down to zero, you know I'm the first one there with an ax.
- |
  

- You can even use my belt to stop the bleeding while I radio Division for help.
- |
  

- Sorry I can't stick around to accompany you to the emergency room, but there's still work that needs to be done, so get me that chopper.
- |
  

- And set up a perimeter right away.
- "To the ladies: Yes, I'm a single father, widowed."
- |
  

- You have to understand, my job takes a heavy toll, and it's hard to maintain a stable relationship.
- |
  

- "If you don't handle stress very well, my advice to you is this: don't date a field agent."
- |
  

- We aren't always around, the hours for my job are highly erratic, and I'm often too tired or traumatized when I get home to make whoopee.
- |
  

- Yes, my life seems glamorous and exciting.
- |
  

- Yes, I exude a brooding sexiness with my skills in unarmed combat and hostage negotiation.
- |
  

- However, if you are forced to spend one whole day and night with me, you may not like everything you see.
- |
  

- But damn it, I get results.
- "To my enemies: If I need information from you, seconds count."
- |
  

- So apologies in advance if I have to break your thumbs or threaten to kill your family; I empathize with you.
- |
  

- Believe me, I've been tortured plenty of times myself, and I know interrogation ain't no picnic.
- |
  

- "Please listen to me very carefully: I will DO WHATEVER IT TAKES to stop this assassination/nuclear bomb/horrible karaoke."
- P.
- S.
- |
  

- Feel free to add me to your friends list!
- |
  

- Send me a detailed message first (preferably encrypted) with your full background information and a recent photo.
- |
  

- I will reply within 24 hours with instructions as to how to proceed from there.
- |
  

- Understand that if you deviate from my orders in any way, I will be forced to place you on the "Ignore/Block User" list. Are we clear?
- |
  

downcase_name: .about.me..on.jack.bauer..rofile_by.jack.ruenprapa
author: By Jack Ruenprapan
title: "\"About Me\" on Jack Bauer's Friendster Profile"
text: |-
  BY  JACK RUENPRAPAN
  - - - -
  I don't have a lot of time to explain right now, but you're going to have to trust me.
  During my years of covert government service, I have gone through hell and back. Yes, I am proud to have served my country, helping to avoid many horrific tragedies. Rules are meant to be followed, but I have a history of insubordination. While the methods I employ may seem harsh, I always have one goal in mind: saving lives. In the process, I have had to make some tough decisions, often within seconds, in order to avert disaster.
  To my friends: I'm sorry for not telling you everything. It's not that I don't trust you, but we are operating on a strict need-to-know basis. But when I'm in a jam, I hope I can count on you. Whether it's illegally hacking passwords of suspected terrorist financiers or keeping your mouth shut about my smack habit, I really appreciate everything. And if you ever find yourself unavoidably chained to a weapon of mass destruction counting down to zero, you know I'm the first one there with an ax. You can even use my belt to stop the bleeding while I radio Division for help. Sorry I can't stick around to accompany you to the emergency room, but there's still work that needs to be done, so get me that chopper. And set up a perimeter right away.
  To the ladies: Yes, I'm a single father, widowed. You have to understand, my job takes a heavy toll, and it's hard to maintain a stable relationship. If you don't handle stress very well, my advice to you is this: don't date a field agent. We aren't always around, the hours for my job are highly erratic, and I'm often too tired or traumatized when I get home to make whoopee. Yes, my life seems glamorous and exciting. Yes, I exude a brooding sexiness with my skills in unarmed combat and hostage negotiation. However, if you are forced to spend one whole day and night with me, you may not like everything you see. But damn it, I get results.
  To my enemies: If I need information from you, seconds count. So apologies in advance if I have to break your thumbs or threaten to kill your family; I empathize with you. Believe me, I've been tortured plenty of times myself, and I know interrogation ain't no picnic. Please listen to me very carefully: I will DO WHATEVER IT TAKES to stop this assassination/nuclear bomb/horrible karaoke.
  P.S. Feel free to add me to your friends list! Send me a detailed message first (preferably encrypted) with your full background information and a recent photo. I will reply within 24 hours with instructions as to how to proceed from there. Understand that if you deviate from my orders in any way, I will be forced to place you on the "Ignore/Block User" list. Are we clear?
  - - - -
date: 2/7/06
article_url: http://mcsweeneys.net/2006/2/7ruenprapan.html
article_size: 2720
