--- 
lines: 
- BY  ADRIAN CHEN
- |
  

- "BEAST: I spy with my little eye, something ."
- |
  

- "FALSE PROPHET: Let's see ."
- |
  

- "BEAST: Yes."
- |
  

- "BEAST: I spy with my little eye, something ."
- |
  

- "FALSE PROPHET: Is it the lake of fire?"
- "BEAST: No."
- "FALSE PROPHET: Is it my shirt?"
- "BEAST: No."
- "FALSE PROPHET: Wow, this one's hard."
- "BEAST: Oh, wait."
- |
  

- It actually was the lake of fire.
- |
  

- "BEAST: I spy with my little eye, something ."
- |
  

- "FALSE PROPHET: The lake of fire!"
- "BEAST: No."
- "FALSE PROPHET: The fire in your hair?"
- "BEAST: No."
- "FALSE PROPHET: The fire burning your eyeballs?"
- "BEAST: No."
- "FALSE PROPHET: The fire burning  my  eyeballs?"
- "BEAST: No."
- "FALSE PROPHET: Jeez, I give up."
- "BEAST: It's fire."
- "FALSE PROPHET: Like fire in general?"
- "BEAST: Yeah."
- |
  

- Just .
- |
  

- "FALSE PROPHET: Oh."
- |
  

- Good one.
- |
  

- "BEAST: I spy with my little eye, something ."
- |
  

- "FALSE PROPHET: Orange?"
- "BEAST: Yes, orange."
- "FALSE PROPHET: Is it an orange?"
- "BEAST: No."
- "FALSE PROPHET: The lake of fire?"
- "BEAST: Close, but no."
- "FALSE PROPHET: Is it just the orange part of the lake of fire?"
- "BEAST: Yes."
- "FALSE PROPHET: !"
- |
  

downcase_name: .i.spy..in.hell_by.adrian.chen
author: By Adrian Chen
title: "\"I Spy\" in Hell"
text: |-
  BY  ADRIAN CHEN
  - - - -
  BEAST: I spy with my little eye, something ... red.
  FALSE PROPHET: Let's see ... is it the lake of fire and brimstone?
  BEAST: Yes.
  - - - -
  BEAST: I spy with my little eye, something ... red.
  FALSE PROPHET: Is it the lake of fire?
  BEAST: No.
  FALSE PROPHET: Is it my shirt?
  BEAST: No.
  FALSE PROPHET: Wow, this one's hard.
  BEAST: Oh, wait. It actually was the lake of fire.
  - - - -
  BEAST: I spy with my little eye, something ... red.
  FALSE PROPHET: The lake of fire!
  BEAST: No.
  FALSE PROPHET: The fire in your hair?
  BEAST: No.
  FALSE PROPHET: The fire burning your eyeballs?
  BEAST: No.
  FALSE PROPHET: The fire burning  my  eyeballs?
  BEAST: No.
  FALSE PROPHET: Jeez, I give up.
  BEAST: It's fire.
  FALSE PROPHET: Like fire in general?
  BEAST: Yeah. Just ... all the fire, everywhere.
  FALSE PROPHET: Oh. Good one.
  - - - -
  BEAST: I spy with my little eye, something ... orange.
  FALSE PROPHET: Orange?
  BEAST: Yes, orange.
  FALSE PROPHET: Is it an orange?
  BEAST: No.
  FALSE PROPHET: The lake of fire?
  BEAST: Close, but no.
  FALSE PROPHET: Is it just the orange part of the lake of fire?
  BEAST: Yes.
  FALSE PROPHET: !!!
  - - - -
date: 3/18/08
article_url: http://mcsweeneys.net/2008/3/18chen.html
article_size: 1133
