--- 
lines: 
- BY  JASON RHODE
- |
  

- IOHANNESRex has invited BAR0|\|z1215 to the "Runnymede" chatroom&#62;
- "IOHANNESRex: HEY"
- "BAR0|\\|z1215: EM?"
- "IOHANNESRex: --- I @m /\\w4Y, FIGhTiNg the FrEnCH!"
- |
  

- "BAR0|\\|z1215: WTF"
- "IOHANNESRex: --- I @m /\\w4Y, FIGhTiNg the FrEnCH!"
- |
  

- "BAR0|\\|z1215: BTDT"
- "IOHANNESRex: HEY whos this"
- "IOHANNESRex: asl?"
- "BAR0|\\|z1215: umm"
- "BAR0|\\|z1215: ru gay d00d"
- |
  

- IOHANNESRex has warned BAR0|\|z1215&#62;
- "IOHANNESRex: LOLLL!"
- |
  

- "IOHANNESRex: chek out my facebook, im under chad divineright ."
- |
  

- "BAR0|\\|z1215: k"
- "BAR0|\\|z1215: hey so wut happened to ur band?"
- |
  

- "IOHANNESRex: Lakkland broke up ."
- |
  

- "IOHANNESRex: my new bands calld softswordd were gonna be emo LMAO"
- "BAR0|\\|z1215: ."
- |
  

- "IOHANNES Rex: shit"
- "IOHANNESRex: mom"
- "IOHANNESRex: brb"
- "BAR0|\\|z1215: k"
- "IOHANNESRex: closecall it wuz the chruch"
- "IOHANNESRex: 3{:-[)&#62; &#60;---thats my cRoWn"
- "BAR0|\\|z1215: ."
- |
  

- I hv HMWRK!
- |
  

- "IOHANNESRex: hey so tht mnz kan i borrow sum $$$$"
- "IOHANNESRex:  [E&#60;D"
- "BAR0|\\|z1215: NW U nvr pay me back"
- "IOHANNESRex: I tryn 2 level my char 4 10p a week srsrlly ok"
- "BAR0|\\|z1215: alrite but u hv 2 me a fvr k?"
- "BAR0|\\|z1215: or else no"
- "IOHANNESRex: cmon"
- "IOHANNESRex: pleeeeeease"
- "IOHANNESRex: k"
- |
  

- BAR0|\|z1215 is trying to send IOHANNESRex a File "magnacarta.
- |
  

- "\"&#62;"
- "IOHANNESRex: got it"
- "IOHANNESRex: WTF?"
- |
  

- WTF?
- |
  

- "IOHANNESRex: im confused wut lol"
- "BAR0|\\|z1215: gimme a sec im invitin sUm peepz"
- "IOHANNESRex: S000 tihs is a zine?"
- |
  

- William d'Albini has joined "Runnymede" chatroom&#62;
- |
  

- Roger Bigod, Earl of Norfolk and Suffolk, has joined "Runnymede" chatroom&#62;
- |
  

- Hugh Bigod, heir to the earldoms of Norfolk and Suffolk, has joined "Runnymede" chatroom&#62;
- |
  

- Henry de Bohun, Earl of Hereford, has joined "Runnymede" chatroom&#62;
- |
  

- Richard de Clare, Earl of Hertford, has joined "Runnymede" chatroom&#62;
- |
  

- Gilbert de Clare, heir to the earldom of Hertford, has joined "Runnymede" chatroom&#62;
- |
  

- John FitzRobert, Lord of Warkworth Castle, has joined "Runnymede" chatroom&#62;
- |
  

- Robert Fitzwalter, Lord of Dunmow Castle, has joined "Runnymede" chatroom&#62;
- "BAR0|\\|z1215: sgn it kplzthx"
- "IOHANNESRex: no way mofosz"
- |
  

- BAR0|\|z1215 has warned IOHANNESRex&#62;
- |
  

- Robert Fitzwalter, Lord of Dunmow Castle, has warned IOHANNESRex&#62;
- |
  

- John FitzRobert, Lord of Warkworth Castle, has warned IOHANNESRex&#62;
- |
  

- Gilbert de Clare, heir to the earldom of Hertford, has warned IOHANNESRex&#62;
- |
  

- Richard de Clare, Earl of Hertford, has warned IOHANNESRex&#62;
- |
  

- Henry de Bohun, Earl of Hereford, has warned IOHANNESRex&#62;
- |
  

- Hugh Bigod, heir to the earldoms of Norfolk and Suffolk, has warned IOHANNESRex&#62;
- |
  

- Roger Bigod, Earl of Norfolk and Suffolk, has warned IOHANNESRex&#62;
- |
  

- William d'Albini has warned IOHANNESRex&#62;
- "IOHANNESRex: Concesserimus libertates quasdam scriptas in Magna Carta nostra de libertatibus."
- |
  

- Data per manum nostram.
- "BAR0|\\|z1215: ROTFLMAO!"
- |
  

- "IOHANNESRex: man fukk u guyz"
- |
  

downcase_name: .im.agna.carta_by.jason.rhode
author: By Jason Rhode
title: (IM)agna Carta
text: |-
  BY  JASON RHODE
  - - - -
  &#60;IOHANNESRex has invited BAR0|\|z1215 to the "Runnymede" chatroom&#62;
  IOHANNESRex: HEY
  BAR0|\|z1215: EM?
  IOHANNESRex: --- I @m /\w4Y, FIGhTiNg the FrEnCH! ill brb ---
  BAR0|\|z1215: WTF
  IOHANNESRex: --- I @m /\w4Y, FIGhTiNg the FrEnCH! ill brb ---
  BAR0|\|z1215: BTDT
  IOHANNESRex: HEY whos this
  IOHANNESRex: asl?
  BAR0|\|z1215: umm
  BAR0|\|z1215: ru gay d00d
  &#60;IOHANNESRex has warned BAR0|\|z1215&#62;
  IOHANNESRex: LOLLL!!!!
  IOHANNESRex: chek out my facebook, im under chad divineright ... its a faker!!!
  BAR0|\|z1215: k
  BAR0|\|z1215: hey so wut happened to ur band??
  IOHANNESRex: Lakkland broke up ... thot ud heard
  IOHANNESRex: my new bands calld softswordd were gonna be emo LMAO
  BAR0|\|z1215: ... god ur gay
  IOHANNES Rex: shit
  IOHANNESRex: mom
  IOHANNESRex: brb
  BAR0|\|z1215: k
  IOHANNESRex: closecall it wuz the chruch
  IOHANNESRex: 3{:-[)&#62; &#60;---thats my cRoWn
  BAR0|\|z1215: ... I hv HMWRK!!!1111
  IOHANNESRex: hey so tht mnz kan i borrow sum $$$$
  IOHANNESRex:  [E&#60;D
  BAR0|\|z1215: NW U nvr pay me back
  IOHANNESRex: I tryn 2 level my char 4 10p a week srsrlly ok
  BAR0|\|z1215: alrite but u hv 2 me a fvr k?
  BAR0|\|z1215: or else no
  IOHANNESRex: cmon
  IOHANNESRex: pleeeeeease
  IOHANNESRex: k
  &#60;BAR0|\|z1215 is trying to send IOHANNESRex a File "magnacarta.parchment"&#62;
  IOHANNESRex: got it
  IOHANNESRex: WTF???!!  WTF???!
  IOHANNESRex: im confused wut lol
  BAR0|\|z1215: gimme a sec im invitin sUm peepz
  IOHANNESRex: S000 tihs is a zine?
  &#60;William d'Albini has joined "Runnymede" chatroom&#62;
  &#60;Roger Bigod, Earl of Norfolk and Suffolk, has joined "Runnymede" chatroom&#62;
  &#60;Hugh Bigod, heir to the earldoms of Norfolk and Suffolk, has joined "Runnymede" chatroom&#62;
  &#60;Henry de Bohun, Earl of Hereford, has joined "Runnymede" chatroom&#62;
  &#60;Richard de Clare, Earl of Hertford, has joined "Runnymede" chatroom&#62;
  &#60;Gilbert de Clare, heir to the earldom of Hertford, has joined "Runnymede" chatroom&#62;
  &#60;John FitzRobert, Lord of Warkworth Castle, has joined "Runnymede" chatroom&#62;
  &#60;Robert Fitzwalter, Lord of Dunmow Castle, has joined "Runnymede" chatroom&#62;
  BAR0|\|z1215: sgn it kplzthx
  IOHANNESRex: no way mofosz
  &#60;BAR0|\|z1215 has warned IOHANNESRex&#62;
  &#60;Robert Fitzwalter, Lord of Dunmow Castle, has warned IOHANNESRex&#62;
  &#60;John FitzRobert, Lord of Warkworth Castle, has warned IOHANNESRex&#62;
  &#60;Gilbert de Clare, heir to the earldom of Hertford, has warned IOHANNESRex&#62;
  &#60;Richard de Clare, Earl of Hertford, has warned IOHANNESRex&#62;
  &#60;Henry de Bohun, Earl of Hereford, has warned IOHANNESRex&#62;
  &#60;Hugh Bigod, heir to the earldoms of Norfolk and Suffolk, has warned IOHANNESRex&#62;
  &#60;Roger Bigod, Earl of Norfolk and Suffolk, has warned IOHANNESRex&#62;
  &#60;William d'Albini has warned IOHANNESRex&#62;
  IOHANNESRex: Concesserimus libertates quasdam scriptas in Magna Carta nostra de libertatibus. Data per manum nostram.
  BAR0|\|z1215: ROTFLMAO!!!!!!!!
  IOHANNESRex: man fukk u guyz
  - - - -
date: 4/25/08
article_url: http://mcsweeneys.net/2008/4/25rhode.html
article_size: 3008
