--- 
lines: 
- |
  

- "These days, we're really very near to a dependable schedule with these things\x97here it is, pretty much three months after the advent of  McSweeney's  Issue 20, and Issue 21 not only exists,  it's actually available ."
- |
  

- It's not on the wrong boat, or held up in Canadian customs; it's in bookstores, like a working quarterly.
- |
  

- "So, for those of you out there who thought of us as some kind of quirky triannual, with issues that stayed current for either five months or two\x97we are punctual now."
- |
  

- Or for now, at least.
- At any rate, there's a lot to talk about here, with our 21st quarterly held delicately in our hands and a team of agitated beat reporters standing before us, ready to run to the wires at the first newsworthy word.
- |
  

- We'll go from the outside in.
- "The outside: Any one of eight ornate covers, all of them slight alterations on the others\x97the crowded laboratory that graces your copy will, on careful inspection, prove to be deftly shifted in one direction or another on your grandmother's, causing no end of familial wonderment."
- |
  

- And just when you've accepted this subtle incongruence, one of you will discover the retractable flap that allows every cover to be converted into a 360-degree panorama, an unbroken view of an immersive little world.
- |
  

- "Yes, you read that correctly: we have invented an endless cover."
- |
  

- By 2012, this will surely be common publishing practice, and future generations will be unable to even imagine the 340-degree covers that ruled the first half-millennium of bookmaking.
- |
  

- Treasure your presence at this pivot of transition, teetering upon the precipice of totality.
- |
  

- Moments like these are positively Gladwellian.
- "And on the inside: Fourteen writers, including Roddy Doyle, Miranda July, Peter Orner, Joyce Carol Oates, Arthur Bradford, Yannick Murphy, and Stephen Elliott, each of whom wrote something excellent about an island off the coast of New Zealand or being bitten by a snake at a wedding or Prince William or any number of other compelling, present-day topics."
- |
  

- To supersaturate the solution, each piece is buttressed with a pertinent storyboard and an unrelated letter to Ray Charles from one of several real people we don't know.
- |
  

- The stories are uniformly great, and the supplementary stuff either sheds light on the writing or suggests something unsettling about the minds of our fellow men.
- |
  

- "This one is packed to the seams, basically\x97there's not a blank page in it until the end, somewhere around page 284."
- |
  

- "And, since we made it a paperback, it's also our most affordable quarterly since Issue 14\x97just $16 in our store and elsewhere."
- |
  

- Below, you can read the first few pages of Peter Orner's story; the full issue can be found  here .
- |
  

- Expect Issue 22 to arrive exactly three months to the minute from the moment you finish reading this.
- |
  

- AN EXCERPT FROM
- "\"PAMPKIN'S LAMENT\""
- BY PETER ORNER.
- |
  

- "Two-term governor Cheeky Al Thorstenson was so popular that year that his Democratic challenger could have been, my father said, Ricardo Montalb\xE1n in his prime and it wouldn't have made a 5 percent difference."
- |
  

- Even so, somebody had to run, somebody always has to run, and so Mike Pampkin put his sacrificial head into the race, and my father, equally for no good reason other than somebody must always prepare the lamb for the slaughter, got himself hired campaign manager.
- |
  

- Nobody understood it all better than Pampkin himself.
- |
  

- He wore his defeat right there on his body, like one of his unflattering V-neck sweaters that made his breasts mound outward like a couple of sad little hills.
- |
  

- When he forced himself to smile for photographers, Pampkin always looked constipated.
- |
  

- And he was so endearingly down-homely honest about his chances that people loved him.
- |
  

- Of course, not enough to vote for him.
- |
  

- Still, for such an ungraceful man he had long, elegant hands, Jackie O hands, my father said, only Pampkin's weren't gloved.
- |
  

- Mike Pampkin's hands were unsheathed, out in the open for the world to see.
- |
  

- He was the loneliest-seeming man ever to run for statewide office in Illinois.
- It was 1980.
- |
  

- I was a mostly ignored 13-year-old and I had already developed great disdain for politics.
- |
  

- It bored me to hatred.
- |
  

- But if I could have voted, I must say I would have voted for Cheeky Al also.
- |
  

- His commercials were very good and I liked his belt buckles.
- |
  

- Everybody liked Cheeky Al's belt buckles.
- Probably what is most remembered, if anything, about Mike Pampkin during that campaign was an incident that happened in Waukegan during the Fourth of July parade.
- |
  

- Pampkin got run over by a fez-wearing Shriner on a motorized flying carpet.
- |
  

- "The Shriner swore it was an accident, but this didn't stop the  Waukegan News Sun  from running the headline: PAMPKIN SWEPT UNDER RUG."
- My memory of that time is of less public humiliation.
- One night, it must have been a few weeks before Election Day, there was a knock on our back door.
- |
  

- It was after 2 in the morning.
- |
  

- The knock was mousy but insistent.
- |
  

- I first heard it in my restless dreams, like someone was tapping on my skull with a pencil.
- |
  

- Eventually, my father answered the door.
- |
  

- I got out of bed and went downstairs.
- |
  

- I found them facing each other at the kitchen table.
- |
  

- If either Pampkin or my father noticed me, they didn't let on.
- |
  

- I crouched on the floor and leaned against the cold stove.
- |
  

- My father was going on as only my father could go on.
- |
  

- To him, at this late stage, the election had become, if not an actual race, not a total farce either.
- |
  

- The flying-carpet incident had caused a small sympathy bump in the polls, and the bump had held.
- Yet it was more than this.
- |
  

- Politics drugged my father.
- |
  

- He loved nothing more than to hear his own voice holding forth, and he'd work himself up into a hallucinatory frenzy of absolute certainty when it came to anything electoral.
- |
  

- My mother left him during the '72 primaries.
- |
  

- My father had ordained that Scoop Jackson was the party's savior, the only one who could save the Democrats from satanic George Wallace.
- |
  

- My mother, treasonably, was for Edmund Muskie, that pantywaist.
- |
  

- The marriage couldn't last, and it didn't.
- |
  

- After the New Hampshire primary, my mother moved to Santa Barbara.
- My father in the kitchen in October of 1980, rattling off to Pampkin what my father called "issue conflagrations," by which he meant those issues that divided city voters from downstaters. To my father, anybody who didn't live in Chicago or the suburbs was a downstater, even if they lived upstate, across state, or on an island in the Kankakee River. He told Pampkin that his position on the Zion nuclear power plant was too wishy-washy, that the anti-nuke loons were getting ready to fry him in vegetable oil.
- "\"Listen, Mike, it doesn't matter that Cheeky Al's all for plutonium in our cheeseburgers."
- |
  

- The only meat those cannibals eat is their own kind.
- Pampkin wasn't listening.
- |
  

- He was staring out the kitchen window, at his own face in the glass.
- |
  

- He didn't seem tired or weary or anything like that.
- |
  

- If anything, he was too awake.
- |
  

- In fact, his eyes were so huge they looked torn open.
- |
  

- Of course, he knew everything my father was saying.
- |
  

- Pampkin wasn't a neophyte.
- |
  

- He'd grown up in the bosom of the machine, in the 24th Ward.
- |
  

- Izzy Horowitz and Jake Arvey were his mentors.
- |
  

- He'd worked his way up, made a life in politics, nothing flashy, steady.
- |
  

- Daley himself was a personal friend.
- |
  

- And when the mayor asks you to take a fall to Cheeky Al, you take a fall to Cheeky Al.
- |
  

- That Daley was dead and buried now didn't make a difference.
- |
  

- A promise to the mayor is a promise to the mayor and there is only one mayor.
- |
  

- Pampkin didn't need my father's issue conflagrations.
- |
  

- He was a man who filled a suit.
- |
  

- Didn't a man have to fill something?
- |
  

- At the time he ran, I think Pampkin was state comptroller, whatever that means.
- |
  

downcase_name: .n.mero.veintiuno._
author: ""
title: "\xA1N\xFAmero Veintiuno!"
text: "- - - -\n\
  These days, we're really very near to a dependable schedule with these things\x97here it is, pretty much three months after the advent of  McSweeney's  Issue 20, and Issue 21 not only exists,  it's actually available . It's not on the wrong boat, or held up in Canadian customs; it's in bookstores, like a working quarterly. So, for those of you out there who thought of us as some kind of quirky triannual, with issues that stayed current for either five months or two\x97we are punctual now. Or for now, at least.\n\
  At any rate, there's a lot to talk about here, with our 21st quarterly held delicately in our hands and a team of agitated beat reporters standing before us, ready to run to the wires at the first newsworthy word. We'll go from the outside in.\n\
  The outside: Any one of eight ornate covers, all of them slight alterations on the others\x97the crowded laboratory that graces your copy will, on careful inspection, prove to be deftly shifted in one direction or another on your grandmother's, causing no end of familial wonderment. And just when you've accepted this subtle incongruence, one of you will discover the retractable flap that allows every cover to be converted into a 360-degree panorama, an unbroken view of an immersive little world. Yes, you read that correctly: we have invented an endless cover. By 2012, this will surely be common publishing practice, and future generations will be unable to even imagine the 340-degree covers that ruled the first half-millennium of bookmaking. Treasure your presence at this pivot of transition, teetering upon the precipice of totality. Moments like these are positively Gladwellian.\n\
  And on the inside: Fourteen writers, including Roddy Doyle, Miranda July, Peter Orner, Joyce Carol Oates, Arthur Bradford, Yannick Murphy, and Stephen Elliott, each of whom wrote something excellent about an island off the coast of New Zealand or being bitten by a snake at a wedding or Prince William or any number of other compelling, present-day topics. To supersaturate the solution, each piece is buttressed with a pertinent storyboard and an unrelated letter to Ray Charles from one of several real people we don't know. The stories are uniformly great, and the supplementary stuff either sheds light on the writing or suggests something unsettling about the minds of our fellow men. This one is packed to the seams, basically\x97there's not a blank page in it until the end, somewhere around page 284. And, since we made it a paperback, it's also our most affordable quarterly since Issue 14\x97just $16 in our store and elsewhere. Below, you can read the first few pages of Peter Orner's story; the full issue can be found  here . Expect Issue 22 to arrive exactly three months to the minute from the moment you finish reading this.\n\
  - - - -\n\
  AN EXCERPT FROM\n\
  \"PAMPKIN'S LAMENT\"\n\
  BY PETER ORNER.\n\
  - - - -\n\
  Two-term governor Cheeky Al Thorstenson was so popular that year that his Democratic challenger could have been, my father said, Ricardo Montalb\xE1n in his prime and it wouldn't have made a 5 percent difference. Even so, somebody had to run, somebody always has to run, and so Mike Pampkin put his sacrificial head into the race, and my father, equally for no good reason other than somebody must always prepare the lamb for the slaughter, got himself hired campaign manager. Nobody understood it all better than Pampkin himself. He wore his defeat right there on his body, like one of his unflattering V-neck sweaters that made his breasts mound outward like a couple of sad little hills. When he forced himself to smile for photographers, Pampkin always looked constipated. And he was so endearingly down-homely honest about his chances that people loved him. Of course, not enough to vote for him. Still, for such an ungraceful man he had long, elegant hands, Jackie O hands, my father said, only Pampkin's weren't gloved. Mike Pampkin's hands were unsheathed, out in the open for the world to see. He was the loneliest-seeming man ever to run for statewide office in Illinois.\n\
  It was 1980. I was a mostly ignored 13-year-old and I had already developed great disdain for politics. It bored me to hatred. But if I could have voted, I must say I would have voted for Cheeky Al also. His commercials were very good and I liked his belt buckles. Everybody liked Cheeky Al's belt buckles.\n\
  Probably what is most remembered, if anything, about Mike Pampkin during that campaign was an incident that happened in Waukegan during the Fourth of July parade. Pampkin got run over by a fez-wearing Shriner on a motorized flying carpet. The Shriner swore it was an accident, but this didn't stop the  Waukegan News Sun  from running the headline: PAMPKIN SWEPT UNDER RUG.\n\
  My memory of that time is of less public humiliation.\n\
  One night, it must have been a few weeks before Election Day, there was a knock on our back door. It was after 2 in the morning. The knock was mousy but insistent. I first heard it in my restless dreams, like someone was tapping on my skull with a pencil. Eventually, my father answered the door. I got out of bed and went downstairs. I found them facing each other at the kitchen table. If either Pampkin or my father noticed me, they didn't let on. I crouched on the floor and leaned against the cold stove. My father was going on as only my father could go on. To him, at this late stage, the election had become, if not an actual race, not a total farce either. The flying-carpet incident had caused a small sympathy bump in the polls, and the bump had held.\n\
  Yet it was more than this. Politics drugged my father. He loved nothing more than to hear his own voice holding forth, and he'd work himself up into a hallucinatory frenzy of absolute certainty when it came to anything electoral. My mother left him during the '72 primaries. My father had ordained that Scoop Jackson was the party's savior, the only one who could save the Democrats from satanic George Wallace. My mother, treasonably, was for Edmund Muskie, that pantywaist. The marriage couldn't last, and it didn't. After the New Hampshire primary, my mother moved to Santa Barbara.\n\
  My father in the kitchen in October of 1980, rattling off to Pampkin what my father called \"issue conflagrations,\" by which he meant those issues that divided city voters from downstaters. To my father, anybody who didn't live in Chicago or the suburbs was a downstater, even if they lived upstate, across state, or on an island in the Kankakee River. He told Pampkin that his position on the Zion nuclear power plant was too wishy-washy, that the anti-nuke loons were getting ready to fry him in vegetable oil.\n\
  \"Listen, Mike, it doesn't matter that Cheeky Al's all for plutonium in our cheeseburgers. The only meat those cannibals eat is their own kind.\"\n\
  Pampkin wasn't listening. He was staring out the kitchen window, at his own face in the glass. He didn't seem tired or weary or anything like that. If anything, he was too awake. In fact, his eyes were so huge they looked torn open. Of course, he knew everything my father was saying. Pampkin wasn't a neophyte. He'd grown up in the bosom of the machine, in the 24th Ward. Izzy Horowitz and Jake Arvey were his mentors. He'd worked his way up, made a life in politics, nothing flashy, steady. Daley himself was a personal friend. And when the mayor asks you to take a fall to Cheeky Al, you take a fall to Cheeky Al. That Daley was dead and buried now didn't make a difference. A promise to the mayor is a promise to the mayor and there is only one mayor. Pampkin didn't need my father's issue conflagrations. He was a man who filled a suit. Didn't a man have to fill something? At the time he ran, I think Pampkin was state comptroller, whatever that means.\n\
  - - - -"
date: 11/1/06
article_url: http://mcsweeneys.net/2006/11/1issue21.html
article_size: 7738
