--- 
lines: 
- BY NICK HORNBY
- |
  

- In celebration of the release of Nick Hornby's   Songbook  , we will be publishing brand-new essays all this week on the subject of favorite songs.
- |
  

- Today's is from Mr. Hornby, and does not appear in his book, or anywhere else that we know of.
- |
  

- We hope you enjoy it.
- |
  

- A long time ago, when I was still teaching English to foreign students in a London language school, I gave private conversation lessons to an unhappy man who called himself Edward, even though that wasn't his name.
- |
  

- Edward was an African living in Rome, where he was a foreign correspondent for his home-town newspaper, and he was unhappy because he was going through a divorce.
- |
  

- "But he was lucid in his unhappiness: he talked with regret, of course, but also with insight, and enormous intelligence, and his melancholy took him off to all sorts of interesting conversational places &mdash; places I never normally got to visit in the normal run of things."
- |
  

- I remember the concentration our talks required, and the stillness and intensity they engendered; I knew that he was in pain, but when our fifty minutes were over I felt invigorated and inspired.
- |
  

- When it was time for him to return to Rome, he asked me to go and stay with him, and I accepted the invitation.
- But when I got there, a few weeks later, he wasn't unhappy any more.
- |
  

- "He was revelling in his status as a single man, a status that, apparently, required very little self-reflection or intelligence: on the night I arrived, I found that he'd fixed us up with a couple of call-girls."
- |
  

- I copped out, in my prissy English way, but he disappeared for forty-eight hours (leaving me with sole use of a beautiful apartment in the centre of Rome); when he came back, he told me he was engaged.
- Some people are at their best when they're miserable.
- |
  

- Ryan Adams's beautiful  Heartbreaker  album is, I suspect, the product of a great deal of pain, and "Oh My Sweet Carolina" is its perfect, still centre, its faint heartbeat, a song so quiet that you don't want to breathe throughout its duration. (It helps that Adams got Emmylou Harris, the best harmony vocalist in the history of pop music, to sing with him on it.) On Adams's next album,  Gold , he seems to have cheered up, and though that's good news for him, it's bad news for me, just as it was when Edward stopped being miserable. His upbeat songs are fine, but they sound a lot like other people's upbeat songs (you can hear the cheeriest incarnations of the Stones, Dylan and Van Morrison all over  Gold ); his blues gave him distinction.
- What rights do we have here?
- |
  

- Are we entitled to ask other people to be unhappy for our benefit?
- |
  

- After all, there are loads of us, and only one of them.
- |
  

- And how can you be happy, really, if you are only ordinary in your happiness, but extraordinary in your grief?
- |
  

- Is it really worth it?
- |
  

- It sounds harsh, I know, but if you are currently romantically involved with someone with a real talent &mdash; especially a talent for songwriting &mdash; then do us all a favour and dump them.
- |
  

- There might be a  Heartbreaker  &mdash; or a  Blood On The Tracks  or a  Layla  &mdash; in it for all of us.
- |
  

- Thanks.
- |
  

downcase_name: .oh.my.sweet.carolina..by.ryan.adams_by.nick.hornb
author: By Nick Hornby
title: "\"Oh My Sweet Carolina\" by Ryan Adams"
text: |-
  BY NICK HORNBY
  - - - -
  [In celebration of the release of Nick Hornby's   Songbook  , we will be publishing brand-new essays all this week on the subject of favorite songs. Today's is from Mr. Hornby, and does not appear in his book, or anywhere else that we know of. We hope you enjoy it.]
  - - - -
  A long time ago, when I was still teaching English to foreign students in a
  London language school, I gave private conversation lessons to an unhappy
  man who called himself Edward, even though that wasn't his name. Edward was
  an African living in Rome, where he was a foreign correspondent for his
  home-town newspaper, and he was unhappy because he was going through a
  divorce. But he was lucid in his unhappiness: he talked with regret, of
  course, but also with insight, and enormous intelligence, and his melancholy
  took him off to all sorts of interesting conversational places &mdash; places I
  never normally got to visit in the normal run of things. I remember the
  concentration our talks required, and the stillness and intensity they
  engendered; I knew that he was in pain, but when our fifty minutes were over
  I felt invigorated and inspired. When it was time for him to return to Rome,
  he asked me to go and stay with him, and I accepted the invitation.
  But when I got there, a few weeks later, he wasn't unhappy any more. He was
  revelling in his status as a single man, a status that, apparently, required
  very little self-reflection or intelligence: on the night I arrived, I found
  that he'd fixed us up with a couple of call-girls. I copped out, in my
  prissy English way, but he disappeared for forty-eight hours (leaving me
  with sole use of a beautiful apartment in the centre of Rome); when he came
  back, he told me he was engaged.
  Some people are at their best when they're miserable. Ryan Adams's beautiful
   Heartbreaker  album is, I suspect, the product of a great deal of pain, and
  "Oh My Sweet Carolina" is its perfect, still centre, its faint heartbeat, a
  song so quiet that you don't want to breathe throughout its duration. (It
  helps that Adams got Emmylou Harris, the best harmony vocalist in the
  history of pop music, to sing with him on it.) On Adams's next album,  Gold ,
  he seems to have cheered up, and though that's good news for him, it's bad
  news for me, just as it was when Edward stopped being miserable. His upbeat
  songs are fine, but they sound a lot like other people's upbeat songs (you
  can hear the cheeriest incarnations of the Stones, Dylan and Van Morrison
  all over  Gold ); his blues gave him distinction.
  What rights do we have here? Are we entitled to ask other people to be
  unhappy for our benefit? After all, there are loads of us, and only one of
  them. And how can you be happy, really, if you are only ordinary in your
  happiness, but extraordinary in your grief? Is it really worth it? It
  sounds harsh, I know, but if you are currently romantically involved with
  someone with a real talent &mdash; especially a talent for songwriting &mdash; then do
  us all a favour and dump them. There might be a  Heartbreaker  &mdash; or a  Blood
  On The Tracks  or a  Layla  &mdash; in it for all of us. Thanks.
  &nbsp;
  &nbsp;
date: 1/13/03
article_url: http://mcsweeneys.net/2003/01/13hornby.html
article_size: 3157
