--- 
lines: 
- BY  TEDDY WAYNE
- |
  

- Brad Pitt  is reportedly getting irritated by a sound  Angelina Jolie  sometimes makes when she chews food .
- |
  

- Cuba Gooding Jr.
- |
  

- Lucy Liu  is lukewarm about this season's Tuesday-night prime-time offerings .
- |
  

- My friend  Tony  isn't a fan of calamari, it was revealed on Saturday at our local Olive Garden .
- |
  

- Tobey Maguire  still occasionally thinks about his second-grade tormentor  Jason Higgins  ..
- |
  

- Sarah Jessica Parker  prefers October weather to September weather .
- |
  

- John Goodman  can do that thing where you whistle by putting your fingers in your mouth .
- |
  

- Ryan Seacrest  suspects he may have mild lactose intolerance .
- |
  

- "Lara Flynn Boyle  recently Googled \"Boyle Irish ancestry\" ...  Robert De Niro 's iPod Classic is freezing every few days ...  Patrick Dempsey  has a hankering for PB&J with the crusts cut off, just like his mom,  Amanda , used to do\x97paging  Dr. Freud ! ...  Sally Field  really, really likes Origins Oatmeal Facial Scrub ...  Joy Behar  used to be able to do a great  Nixon  impression, can't really anymore ...  Leonardo DiCaprio  has been having nightmares about a three-headed dragon that breathes pink flames ...  Laurence Fishburne  prefers one of his goldfish over the other two ...  Craig Kilborn  just got his car washed ...  Eva Longoria Parker  is having trouble with her upgrade to Windows Vista ...  You  will die a hollow, friendless death ...  Pete Sampras  can't wait for this weekend ..."
- |
  

- Teddy Wayne's
- Other Pieces .
- |
  

downcase_name: .page.six..gets.extremely.personal_by.teddy.wayne
author: By Teddy Wayne
title: "\"Page Six\" Gets Extremely Personal"
text: "BY  TEDDY WAYNE\n\
  - - - -\n\
  Brad Pitt  is reportedly getting irritated by a sound  Angelina Jolie  sometimes makes when she chews food ...  Cuba Gooding Jr.  has stopped following college basketball ...  Lucy Liu  is lukewarm about this season's Tuesday-night prime-time offerings ... My friend  Tony  isn't a fan of calamari, it was revealed on Saturday at our local Olive Garden ...  Tobey Maguire  still occasionally thinks about his second-grade tormentor  Jason Higgins  ...  Sarah Jessica Parker  prefers October weather to September weather ...  John Goodman  can do that thing where you whistle by putting your fingers in your mouth ...  Ryan Seacrest  suspects he may have mild lactose intolerance ...  Lara Flynn Boyle  recently Googled \"Boyle Irish ancestry\" ...  Robert De Niro 's iPod Classic is freezing every few days ...  Patrick Dempsey  has a hankering for PB&J with the crusts cut off, just like his mom,  Amanda , used to do\x97paging  Dr. Freud ! ...  Sally Field  really, really likes Origins Oatmeal Facial Scrub ...  Joy Behar  used to be able to do a great  Nixon  impression, can't really anymore ...  Leonardo DiCaprio  has been having nightmares about a three-headed dragon that breathes pink flames ...  Laurence Fishburne  prefers one of his goldfish over the other two ...  Craig Kilborn  just got his car washed ...  Eva Longoria Parker  is having trouble with her upgrade to Windows Vista ...  You  will die a hollow, friendless death ...  Pete Sampras  can't wait for this weekend ...\n\
  - - - -\n\
  Teddy Wayne's\n\
  Other Pieces .\n\
  - - - -"
date: 3/11/08
article_url: http://mcsweeneys.net/2008/3/11wayne.html
article_size: 1556
