--- 
lines: 
- By  Mike Sacks
- |
  

- "\"What up, chief?"
- "\" asked Larry."
- |
  

- He had just finished soccer practice and was now sucking back on a bottle of his favorite brew, 40-Dog Buzz.
- "\"Nothing, friend,\""
- |
  

- Kyle.
- |
  

- They had been best buds for three years now.
- |
  

- And Kyle knew absolutely everything about Larry, including Larry's intense hunger for "vagina.
- "\"How was math class?"
- "\" asked Larry, trying to get Kyle's goat."
- |
  

- "\"Did you study for that test?"
- "\"Fuck off, bitch!"
- "\" said Kyle."
- |
  

- "\"You know damn well that I didn't study for that test."
- |
  

- What in the world?
- Larry laughed, as he knew that Kyle was merely being facetious.
- |
  

- And besides, "bitch" was a term of endearment when used among good friends and close acquaintances.
- "\"So, are you planning on attending that party tonight?"
- "\" Larry asked."
- "\"Hell yes!"
- "\" answered Kyle."
- "\"Better yet,\""
- |
  

- Larry, "how about that frat party we learned about on the World Wide Web?
- |
  

- The one taking place in Florida?
- |
  

- I'm thinking road trip!
- "Kyle thought for a minute, and then replied: \"'Cause I'm thinking the same."
- |
  

- Let's do it.
- |
  

- And let's invite Janet!
- Larry gave Kyle the high five and then climbed into his tremendous sport utility vehicle, or S.U.
- V.
- |
  

- "\"Kick out the jams, motherfucker!"
- "\" screamed Kyle, from the passenger's seat."
- Larry did as he was asked, and within no time, Limp Bizkit [sic] was blasting from the nine Bose speakers and seven specialized sub-woofers that Larry had installed the previous month.
- |
  

- The sound was absolutely monstrous.
- Larry and Kyle sped off through the university's streets to Janet's dormitory in the western, and more fancy, part of campus.
- |
  

- Janet was already waiting for them.
- |
  

- "She looked ravenous: extremely tight shorts, blue tank-top, open-toe sandals, breasts (soft and large) swinging to and fro."
- |
  

- Exquisite.
- "\"What's the story, boys?"
- "\" Janet asked, climbing into the back seat of the S.U."
- V.
- |
  

- Larry caught a quick glimpse of her tremendous right nipple.
- Larry, Kyle, and Janet had been friends forever.
- |
  

- She treated them like brothers and they, in turn, treated her like a sister.
- |
  

- A sister whose image they could fantasize about and then later, when it was dark, masturbate to.
- "\"Nothin',\""
- |
  

- Kyle, taking a swig from his freshly opened bottle of brewsky.
- |
  

- "\"Just high-tailin' it down to Florida."
- |
  

- For a little of this and that.
- "\"Sweet,\""
- |
  

- Janet, absentmindedly stroking her sweaty tank-top.
- |
  

- "\"Freakin' sweet."
- |
  

- It was a few hours later and Kyle, Larry, and Janet were walking down the main avenue of Fort Lauderdale, searching for the fraternity house they had read about on the AOL.
- |
  

- "\"I'm so high that I could fly,\""
- |
  

- Kyle sarcastically, taking a puff from the marijuana cigarette he had just lit up.
- |
  

- "\"The world is all about colors and love and freedom."
- Larry and Janet laughed.
- |
  

- It was nothing for them to see one of their friends "high," but this was ridiculous.
- "\"Where in the fuck is this party?"
- "\" asked Larry eventually, growing frustrated."
- "\"My god, she's beautiful!"
- "\" declared Kyle, pointing to a large, all-glass house situated directly on the beach."
- |
  

- "\"The fraternity house!"
- |
  

- The answer to all of our dreams!
- Within no time, Larry, Janet, and Kyle were eagerly making their way into the large Gothic-spired mansion.
- |
  

- "What they observed next absolutely amazed them, stunning them beyond belief:"
- Large fraternity types placing compact discs into compact disc players!
- Half-naked women, their breasts jingling and jangling, perched on the shoulders of football players!
- Pyramids, 15 feet high, created with only empty beer cans!
- Pizza pies, half-eaten, lazily strewn across expensive leather couches!
- A rock and roll band playing very loudly!
- A fat man with a beard pouring vodka into a crystal punch bowl!
- "\"Aw, spit!"
- "\" exclaimed Larry."
- |
  

- "\"This is the best fraternity party that I've ever seen!"
- Kyle could only nod.
- |
  

- He agreed, but was too shocked to say anything.
- "Janet, on the other hand, could not stop talking: \"This is incredible, absolutely incredible."
- |
  

- I mean, I've always thought fraternity parties were supposed to be good, but this .
- |
  

- This is excellent!
- Janet stopped talking.
- |
  

- She looked over to Kyle, who looked over to Larry.
- |
  

- And then, without another word, they linked their arms together and walked directly into the amazing, cacophonous fray.
- |
  

- "\"Peace."
- Kyle turned off his miniature cellular telephone and placed it back into his T-shirt pocket.
- "\"That was the fraternity president,\""
- |
  

- Kyle from the S.U.
- V.
- |
  

- "\"He wanted to thank us for coming to the party."
- |
  

- There sure was a lot of wonderful vagina!
- Janet rolled her eyes.
- |
  

- "\"All I've heard since leaving the party is 'vagina this' and 'vagina that."
- |
  

- Enough!
- "\"Easy, you two,\""
- |
  

- Kyle, flicking on the powerful car-stereo system.
- |
  

- "\"Time to bust out the kick-ass tunes!"
- The sounds of the Red Hot Chili Peppers, a very popular funk and soul band, filled the S.U.
- V.
- "\"Goodnight,\""
- |
  

- Janet, absentmindedly swiping at her sweaty left nipple and then at her right nipple, which was also sweaty.
- |
  

- "\"See you when I see you."
- "\"Until then!"
- "\" exclaimed Kyle."
- "\"On the other side,\""
- |
  

- Larry.
- College life is sweet,  Janet thought, falling into a deep and gentle sleep.
- |
  

- So goddamn sweet that it is motherfuckin' ridiculous.
- |
  

downcase_name: .rockin..it..frat.party.s.hing.author_by.mike.sack
author: By Mike Sacks
title: "\"Rockin' It, Frat-Party Style!\": A Short Story Geared to College Students, Written by a 30-Something Author"
text: |-
  By  Mike Sacks
  - - - -
  "What up, chief?" asked Larry. He had just finished soccer practice and was now sucking back on a bottle of his favorite brew, 40-Dog Buzz.
  "Nothing, friend," said Kyle. They had been best buds for three years now. And Kyle knew absolutely everything about Larry, including Larry's intense hunger for "vagina."
  "How was math class?" asked Larry, trying to get Kyle's goat. "Did you study for that test?"
  "Fuck off, bitch!" said Kyle. "You know damn well that I didn't study for that test. What in the world?"
  Larry laughed, as he knew that Kyle was merely being facetious. And besides, "bitch" was a term of endearment when used among good friends and close acquaintances.
  "So, are you planning on attending that party tonight?" Larry asked.
  "Hell yes!" answered Kyle.
  "Better yet," declared Larry, "how about that frat party we learned about on the World Wide Web? The one taking place in Florida? I'm thinking road trip!"
  Kyle thought for a minute, and then replied: "'Cause I'm thinking the same. Let's do it. And let's invite Janet!"
  Larry gave Kyle the high five and then climbed into his tremendous sport utility vehicle, or S.U.V., complete with the most amazing stereo sound system in the world.
  "Kick out the jams, motherfucker!" screamed Kyle, from the passenger's seat.
  Larry did as he was asked, and within no time, Limp Bizkit [sic] was blasting from the nine Bose speakers and seven specialized sub-woofers that Larry had installed the previous month. The sound was absolutely monstrous.
  Larry and Kyle sped off through the university's streets to Janet's dormitory in the western, and more fancy, part of campus. Janet was already waiting for them. She looked ravenous: extremely tight shorts, blue tank-top, open-toe sandals, breasts (soft and large) swinging to and fro. Exquisite.
  "What's the story, boys?" Janet asked, climbing into the back seat of the S.U.V., but not before Larry caught a quick glimpse of her tremendous right nipple.
  Larry, Kyle, and Janet had been friends forever. She treated them like brothers and they, in turn, treated her like a sister. A sister whose image they could fantasize about and then later, when it was dark, masturbate to.
  "Nothin'," answered Kyle, taking a swig from his freshly opened bottle of brewsky. "Just high-tailin' it down to Florida. For a little of this and that."
  "Sweet," said Janet, absentmindedly stroking her sweaty tank-top. "Freakin' sweet."
  - - - -
  It was a few hours later and Kyle, Larry, and Janet were walking down the main avenue of Fort Lauderdale, searching for the fraternity house they had read about on the AOL.com.
  "I'm so high that I could fly," said Kyle sarcastically, taking a puff from the marijuana cigarette he had just lit up. "The world is all about colors and love and freedom."
  Larry and Janet laughed. It was nothing for them to see one of their friends "high," but this was ridiculous.
  "Where in the fuck is this party?" asked Larry eventually, growing frustrated.
  "My god, she's beautiful!" declared Kyle, pointing to a large, all-glass house situated directly on the beach. "The fraternity house! The answer to all of our dreams!"
  Within no time, Larry, Janet, and Kyle were eagerly making their way into the large Gothic-spired mansion. What they observed next absolutely amazed them, stunning them beyond belief:
  Large fraternity types placing compact discs into compact disc players!
  Half-naked women, their breasts jingling and jangling, perched on the shoulders of football players!
  Pyramids, 15 feet high, created with only empty beer cans!
  Pizza pies, half-eaten, lazily strewn across expensive leather couches!
  A rock and roll band playing very loudly!
  A fat man with a beard pouring vodka into a crystal punch bowl!
  "Aw, spit!" exclaimed Larry. "This is the best fraternity party that I've ever seen!"
  Kyle could only nod. He agreed, but was too shocked to say anything.
  Janet, on the other hand, could not stop talking: "This is incredible, absolutely incredible. I mean, I've always thought fraternity parties were supposed to be good, but this ... this is not good. This is excellent!"
  Janet stopped talking. She looked over to Kyle, who looked over to Larry. And then, without another word, they linked their arms together and walked directly into the amazing, cacophonous fray.
  - - - -
  "Peace."
  Kyle turned off his miniature cellular telephone and placed it back into his T-shirt pocket.
  "That was the fraternity president," exclaimed Kyle from the S.U.V.'s passenger seat. "He wanted to thank us for coming to the party. There sure was a lot of wonderful vagina!"
  Janet rolled her eyes. "All I've heard since leaving the party is 'vagina this' and 'vagina that.' Enough!"
  "Easy, you two," said Kyle, flicking on the powerful car-stereo system. "Time to bust out the kick-ass tunes!"
  The sounds of the Red Hot Chili Peppers, a very popular funk and soul band, filled the S.U.V.
  "Goodnight," said Janet, absentmindedly swiping at her sweaty left nipple and then at her right nipple, which was also sweaty. "See you when I see you."
  "Until then!" exclaimed Kyle.
  "On the other side," responded Larry.
  College life is sweet,  Janet thought, falling into a deep and gentle sleep.  So goddamn sweet that it is motherfuckin' ridiculous.
  - - - -
date: 1/14/05
article_url: http://mcsweeneys.net/2005/1/14feature.html
article_size: 5278
