--- 
lines: 
- "BY  JOS\xE9 AVELINO GILLES CORBETT LOUREN\xE7O"
- |
  

- "The modern forest faces many challenges\x97acid rain, ground-water pollution, and clear-cutting, to name but a few."
- |
  

- Only the strongest and most well-equipped breed of eco-warrior will survive this daunting new era of environmental terrorism.
- |
  

- That's why we're here this weekend.
- |
  

- We have to fight to save our forests, and over the next few days we're going to give you the weapons you'll need so we can win this fight.
- Switchblade
- I've met loggers, large men with large appetites.
- |
  

- "Their canteen breakfasts of flapjacks and maple syrup fuel their giant muscles and fists, which\x97do not be fooled\x97can be obscured by belly fat or thick flannel."
- |
  

- In a manner akin to defending against the attack of the ninja (shrouded by darkness and magic), you must be able to cut through these illusions, and then cut through Achilles tendons.
- |
  

- Big men are less big when prostrate.
- |
  

- "Remember to yell \"Timber\"\x97safety first."
- Pepper Spray
- Have you ever seen a bald eagle's nest?
- |
  

- "Sticks, bark, and soft tufts of human hair\x97from where are these materials sourced?"
- |
  

- The same forest the eagle claims as his home.
- |
  

- "But I ask you this: How many homeowners forage in the rec room for loose drywall and tile with which to spiff up the master bath?"
- |
  

- Very few.
- |
  

- These winged vandals can be slowed if blinded.
- |
  

- Aim for the eyes.
- Harpoon Launcher
- Be cautious near bear cubs.
- |
  

- "An angry mother bear is vicious and swift\x97especially uphill\x97and will chase you down like Tommy Lee Jones."
- |
  

- And don't think you're safe in a tree.
- |
  

- You are just one more tasty coconut to a hungry bear.
- |
  

- My intern, Jeremy, thinks it important to mention that "most, if not all, bears do not eat coconuts.
- "\" I mean, of course bears don't eat coconuts."
- |
  

- I was just making a point.
- |
  

- Perhaps if Jeremy had paid attention to my seminar on the proper operation of the PoonBeam MK-231 at last year's symposium instead of fact-checking my every word, he'd still have full use of both legs.
- Flamethrower
- How many of you have viewed and enjoyed the animated children's program  Alvin and the Chipmunks ?
- |
  

- Raise your hands, please.
- |
  

- In fact, stand up.
- |
  

- You too, Jeremy.
- |
  

- Is that everyone?
- |
  

- Good.
- |
  

- Now, everybody who is sitting, I want you to look at the nearest standing conventioneer and tell him or her "You have been lied to.
- "\" All together now: YOU HAVE BEEN LIED TO."
- |
  

- Cathartic, isn't it?
- Chipmunks do not wear sweater dresses emblazoned with the initial of their given name, they do not wear matching caps, and they certainly do not mingle with human children that are inexplicably the same size they are.
- |
  

- What do chipmunks do?
- |
  

- They steal seeds and nuts and hide them for their own selfish consumption.
- |
  

- Seeds are baby trees, so basically a chipmunk is an H2-driving murderer who hates God.
- |
  

- A great swath of heavenly fire is the preferred extermination technique.
- Retractable Adamantine Claws
- I'm not going to lie to you.
- |
  

- The surgery will be painful, and the unlicensed shadow doctors responsible for said pain will probably attempt to erase your memory of the procedure.
- |
  

- "Also: There's a good chance you will have frequent, terrible nightmares as a result of this."
- |
  

- But on the plus side, you and you alone (along with everyone else who undergoes the operation) will be able to weed the forest floor of aggressive plant life.
- |
  

- This is an honorable calling!
- |
  

- Even the strongest among us do not have the stomach to witness the devastation unchecked chickweed can wreak on the mighty sequoia.
- Taser
- It would be naive to pretend our mission is uncomplicated.
- |
  

- From time to time a member of your team will go berserk while patrolling and refuse to do what must be done to protect the trees.
- |
  

- "When this happens, dissenting voices are best quieted by a tactical SWAT Taser\x97I call it \"The Jiggler."
- "\" Don't have one with you?"
- |
  

- You'll find the 2005 model under your seat.
- Jeremy here will assist me with this demonstration, and then we'll break for lunch.
- |
  

- A big hand for Jeremy, everybody!
- |
  

- He'll be graduating from UC Berkeley with a bachelor of science degree in plant and microbial biology at the end of this semester.
- |
  

- What's that?
- |
  

- Oh, Jeremy wants to know why I've asked him to wear a bib.
- |
  

- Well, I wouldn't want him to get foam down the front of his nice shirt, would I? Ha ha!
- And don't worry if his legs kick about for a moment or two.
- |
  

- He's dedicated to the cause.
- |
  

downcase_name: .save.our.forests..sympos.o.gilles.corbett.louren.
author: "By Jos\xE9 Avelino Gilles Corbett Louren\xE7o"
title: "\"Save Our Forests\" Symposium, Day 1: Opening Remarks"
text: "BY  JOS\xE9 AVELINO GILLES CORBETT LOUREN\xE7O\n\
  - - - -\n\
  The modern forest faces many challenges\x97acid rain, ground-water pollution, and clear-cutting, to name but a few. Only the strongest and most well-equipped breed of eco-warrior will survive this daunting new era of environmental terrorism. That's why we're here this weekend. We have to fight to save our forests, and over the next few days we're going to give you the weapons you'll need so we can win this fight.\n\
  Switchblade\n\
  I've met loggers, large men with large appetites. Their canteen breakfasts of flapjacks and maple syrup fuel their giant muscles and fists, which\x97do not be fooled\x97can be obscured by belly fat or thick flannel. In a manner akin to defending against the attack of the ninja (shrouded by darkness and magic), you must be able to cut through these illusions, and then cut through Achilles tendons. Big men are less big when prostrate. Remember to yell \"Timber\"\x97safety first.\n\
  Pepper Spray\n\
  Have you ever seen a bald eagle's nest? Sticks, bark, and soft tufts of human hair\x97from where are these materials sourced? The same forest the eagle claims as his home. But I ask you this: How many homeowners forage in the rec room for loose drywall and tile with which to spiff up the master bath? Very few. These winged vandals can be slowed if blinded. Aim for the eyes.\n\
  Harpoon Launcher\n\
  Be cautious near bear cubs. An angry mother bear is vicious and swift\x97especially uphill\x97and will chase you down like Tommy Lee Jones. And don't think you're safe in a tree. You are just one more tasty coconut to a hungry bear. My intern, Jeremy, thinks it important to mention that \"most, if not all, bears do not eat coconuts.\" I mean, of course bears don't eat coconuts. I was just making a point. Perhaps if Jeremy had paid attention to my seminar on the proper operation of the PoonBeam MK-231 at last year's symposium instead of fact-checking my every word, he'd still have full use of both legs.\n\
  Flamethrower\n\
  How many of you have viewed and enjoyed the animated children's program  Alvin and the Chipmunks ? Raise your hands, please. In fact, stand up. You too, Jeremy. Is that everyone? Good. Now, everybody who is sitting, I want you to look at the nearest standing conventioneer and tell him or her \"You have been lied to.\" All together now: YOU HAVE BEEN LIED TO. Cathartic, isn't it?\n\
  Chipmunks do not wear sweater dresses emblazoned with the initial of their given name, they do not wear matching caps, and they certainly do not mingle with human children that are inexplicably the same size they are. What do chipmunks do? They steal seeds and nuts and hide them for their own selfish consumption. Seeds are baby trees, so basically a chipmunk is an H2-driving murderer who hates God. A great swath of heavenly fire is the preferred extermination technique.\n\
  Retractable Adamantine Claws\n\
  I'm not going to lie to you. The surgery will be painful, and the unlicensed shadow doctors responsible for said pain will probably attempt to erase your memory of the procedure. Also: There's a good chance you will have frequent, terrible nightmares as a result of this. But on the plus side, you and you alone (along with everyone else who undergoes the operation) will be able to weed the forest floor of aggressive plant life. This is an honorable calling! Even the strongest among us do not have the stomach to witness the devastation unchecked chickweed can wreak on the mighty sequoia.\n\
  Taser\n\
  It would be naive to pretend our mission is uncomplicated. From time to time a member of your team will go berserk while patrolling and refuse to do what must be done to protect the trees. When this happens, dissenting voices are best quieted by a tactical SWAT Taser\x97I call it \"The Jiggler.\" Don't have one with you? You'll find the 2005 model under your seat.\n\
  Jeremy here will assist me with this demonstration, and then we'll break for lunch. A big hand for Jeremy, everybody! He'll be graduating from UC Berkeley with a bachelor of science degree in plant and microbial biology at the end of this semester. What's that? Oh, Jeremy wants to know why I've asked him to wear a bib. Well, I wouldn't want him to get foam down the front of his nice shirt, would I? Ha ha!\n\
  And don't worry if his legs kick about for a moment or two. He's dedicated to the cause.\n\
  - - - -"
date: 8/17/05
article_url: http://mcsweeneys.net/2005/8/17forests.html
article_size: 4315
