--- 
lines: 
- BY  KEN KRIMSTEIN
- |
  

- "FADE IN:"
- A windswept Vancouver wheat field, thin, shy clouds shifting aimlessly across shimmering, obvious hills.
- |
  

- Fred Jones, his cravat, usually so tight and firm, picks his bellbottomed cuffs through the living web, moss, weeds.
- |
  

- Back, over the hill, out of sight, sits the van, the once cheery van, now strangely silent.
- |
  

- Daphne, he scarf proud, sips a milk shake, cold, shimmering, despite the dry winds, nervously flouncing her overdone hair, trying to forget the cold words she said to Fred not twenty minutes before.
- |
  

- Slurp.
- |
  

- Shizzle.
- |
  

- Shplonk.
- Knocks like hollow weeds resound through the vehicle, stationary yet tottering on the aimless edge of a dirt road with no beginning and no end.
- |
  

- "\"Is that you, Norville?"
- "\" Daphne says after a long shlurp contorts her perfect cheeks into convex cavities."
- |
  

- "\"It is I,\""
- |
  

- "\"I, Norville Rogers, aka Shaggy!"
- "\" \""
- Owww waaa rrooooby," echoes Scoobert-Doo, always playing the fool.
- Daphne adjusts her scarf and thinks of Velma, so coy with her glasses off, teasing them all over chamomile tea back at the sun-baked diner in Edmonton, teasing them for their stupidity in not realizing that the culprit was the ghost, always the ghost, every time the ghost.
- |
  

- Why, Daphne thought, why must it always be the ghost?
- |
  

- Why were they trapped in this fool's game of charade and parody?
- |
  

- Why had she given up her job teaching comparative literature at McGill and her Gitane-smoking Russian with his sarcasm and garlic.
- |
  

- Why had she given up the Raleigh three-speed, with the battered basket, just the right size for the loaf of warm bread they would split every morning, why would she give up all that for this, for this clownish van?
- |
  

- For an endless parade of ghosts.
- |
  

- For Fred.
- Angry clouds, now too full, release their moisture in torrents, the tin roof of the Chevrolet beating a retreat, a reveille that tells Daphne this was all there was &#8212; ghosts and milk shakes.
- |
  

- Ghosts and milk shakes.
- |
  

- Fred, as if he could read her mind like the wily ghost, agreed, silently.
- |
  

- Stoically.
- |
  

- Fredishly.
- |
  

downcase_name: .the.anomie.of.my.anomie..ce.munro_by.ken.krimstei
author: By Ken Krimstein
title: "\"The Anomie of My Anomie is My Friend\" a Scooby-Doo Treatment by Alice Munro"
text: |-
  BY  KEN KRIMSTEIN
  - - - -
  FADE IN:
  A windswept Vancouver wheat field, thin, shy clouds shifting aimlessly across shimmering, obvious hills. Fred Jones, his cravat, usually so tight and firm, picks his bellbottomed cuffs through the living web, moss, weeds. Back, over the hill, out of sight, sits the van, the once cheery van, now strangely silent. Daphne, he scarf proud, sips a milk shake, cold, shimmering, despite the dry winds, nervously flouncing her overdone hair, trying to forget the cold words she said to Fred not twenty minutes before. Slurp. Shizzle. Shplonk.
  Knocks like hollow weeds resound through the vehicle, stationary yet tottering on the aimless edge of a dirt road with no beginning and no end. "Is that you, Norville?" Daphne says after a long shlurp contorts her perfect cheeks into convex cavities. "It is I," a voice echoes through the sheet metal emblazoned with bright, once cheerful flowers, "I, Norville Rogers, aka Shaggy!" "Owww waaa rrooooby," echoes Scoobert-Doo, always playing the fool.
  Daphne adjusts her scarf and thinks of Velma, so coy with her glasses off, teasing them all over chamomile tea back at the sun-baked diner in Edmonton, teasing them for their stupidity in not realizing that the culprit was the ghost, always the ghost, every time the ghost. Why, Daphne thought, why must it always be the ghost? Why were they trapped in this fool's game of charade and parody? Why had she given up her job teaching comparative literature at McGill and her Gitane-smoking Russian with his sarcasm and garlic. Why had she given up the Raleigh three-speed, with the battered basket, just the right size for the loaf of warm bread they would split every morning, why would she give up all that for this, for this clownish van? For an endless parade of ghosts. For Fred.
  Angry clouds, now too full, release their moisture in torrents, the tin roof of the Chevrolet beating a retreat, a reveille that tells Daphne this was all there was &#8212; ghosts and milk shakes. Ghosts and milk shakes. Fred, as if he could read her mind like the wily ghost, agreed, silently. Stoically. Fredishly.
  &nbsp;
  &nbsp;
date: 8/12/03
article_url: http://mcsweeneys.net/2003/08/12scooby.html
article_size: 2135
