--- 
lines: 
- BY  TABETHA WELLS
- |
  

- Telephone rings.
- |
  

- Heh-hello, uh, Bannerman Talent Agency .
- |
  

- Um.
- |
  

- Ye-yes.
- |
  

- This is Mr. Bannerman.
- Oh, you have an act you'd, you'd like me to .
- |
  

- Oh.
- |
  

- OK.
- |
  

- Can you describe it to me?
- Ah, I see.
- |
  

- A family act.
- Uh-huh.
- Uh-huh.
- I'm sorry, they what?
- |
  

- Oh.
- |
  

- So the clothes come right off .
- |
  

- Uh-huh.
- Uh-huh.
- Well, I'm not sure the stage manager would want .
- |
  

- OK.
- |
  

- I see.
- I'm sorry, you said three donkeys?
- |
  

- OK.
- Uh-huh.
- Uh-huh.
- Oh dear.
- |
  

- Uh, how .
- |
  

- Uh-huh.
- |
  

- And she already knows how .
- |
  

- That's not the best part?
- |
  

- OK.
- |
  

- What .
- |
  

- Oh dear.
- |
  

- Are you sure that's .
- |
  

- You .
- |
  

- Sometimes with fire.
- Well.
- |
  

- Well, that is ah .
- |
  

- Out of curiosity, what do you call yourselves?
- The .
- |
  

- Aristocrats.
- |
  

- I see.
- |
  

- Well, thanks for calling, but I specialize in entertainment for children's parties.
- Uh-huh.
- Oh, you have another act?
- Uh-huh.
- Uh-huh.
- I'm .
- |
  

- I'm going to stop you right there.
- |
  

- You're describing the same act.
- Ye-yes you are.
- OK, then.
- |
  

- What makes it diff .
- |
  

- OK.
- Uh-huh.
- |
  

- Balloon animals.
- |
  

- I see.
- |
  

- You put them in your .
- |
  

- Well, I still don't .
- |
  

- It's been very .
- |
  

- What?
- |
  

- You .
- |
  

- I, if I have a suggestion .
- |
  

- Um .
- |
  

- I think maybe if you didn't um .
- |
  

- Uh-huh .
- |
  

- Oh.
- |
  

- I didn't, I didn't realize that was .
- |
  

- No, I didn't mean to, I didn't mean to question your artistic in-integrity.
- You .
- |
  

- It's probably better if .
- |
  

- I see it myself .
- |
  

- OK, see you tomorrow at 3.
- What?
- |
  

- Wear a raincoat?
- |
  

- All right, thanks for the .
- |
  

- See you tomorrow.
- |
  

- Buh-bye.
- |
  

downcase_name: .the.aristocrats..as.i.th.rform.it_by.tabetha.well
author: By Tabetha Wells
title: "\"The Aristocrats\" as I Think Bob Newhart Would Perform It"
text: "BY  TABETHA WELLS\n\
  - - - -\n\
  ( Telephone rings. )\n\
  Heh-hello, uh, Bannerman Talent Agency ...\n\
  Um. Ye-yes. This is Mr. Bannerman.\n\
  Oh, you have an act you'd, you'd like me to ... to represent? Oh. OK. Can you describe it to me?\n\
  Ah, I see. A family act.\n\
  Uh-huh.\n\
  Uh-huh.\n\
  I'm sorry, they what? Oh. So the clothes come right off ...\n\
  Uh-huh.\n\
  Uh-huh.\n\
  Well, I'm not sure the stage manager would want ... want you to smear that everywh\x97\n\
  OK. I see.\n\
  I'm sorry, you said three donkeys? OK.\n\
  Uh-huh.\n\
  Uh-huh.\n\
  Oh dear. Uh, how ... how old is your daughter?\n\
  Uh-huh. And she already knows how ... how to ...\n\
  That's not the best part? OK. What ... what is the best part?\n\
  Oh dear. Are you sure that's ... um ... physically possible?\n\
  You ... you do it all the time. Sometimes with fire.\n\
  Well. Well, that is ah ... um ... a very, a very interesting act. Out of curiosity, what do you call yourselves?\n\
  The ... the Aristocrats. I see. Well, thanks for calling, but I specialize in entertainment for children's parties.\n\
  Uh-huh.\n\
  Oh, you have another act?\n\
  Uh-huh.\n\
  Uh-huh.\n\
  I'm ... I'm going to stop you right there. You're describing the same act.\n\
  Ye-yes you are.\n\
  OK, then. What makes it diff ... you were just getting to it ... OK.\n\
  Uh-huh. Balloon animals. I see. You put them in your ... oh ... oh dear ...\n\
  Well, I still don't ... don't think your act is right for us, but thanks for your time. It's been very ... uh ... very interesting, and good luck with ... with your careers.\n\
  What? You ... you are willing to change the act if I, if I have a suggestion ...\n\
  Um ... I think maybe if you didn't um ... have relations with your ... with your daughter ... while she was ... um ... servicing the donkeys ...\n\
  Uh-huh ... Oh. I didn't, I didn't realize that was ... that was the heart of the piece ...\n\
  No, I didn't mean to, I didn't mean to question your artistic in-integrity.\n\
  You ... you're right. It's probably better if ... if I see it myself ...\n\
  OK, see you tomorrow at 3.\n\
  What? Wear a raincoat? All right, thanks for the ... for the tip.\n\
  See you tomorrow. Buh-bye.\n\
  - - - -"
date: 9/8/05
article_url: http://mcsweeneys.net/2005/9/8wells.html
article_size: 2043
