--- 
lines: 
- BY  BENJAMIN COHEN
- |
  

- "The good news is in: Plastics are great."
- |
  

- Stop your bitching.
- |
  

- I've been reading all the research and the problem is you.
- |
  

- No, I'm not anti-environment; I'm anti-environmentalist.
- |
  

- It's like that line, right?
- |
  

- You shoot messengers?
- This whole thing, I'm with crack reporter John Tierney, our friend at the  Times  over there debunking pointless concerns from Crocs-wearing pansies.
- |
  

- Those alarmists have complained for years that unsightly gobs of plastic bags won't deteriorate for centuries.
- |
  

- In landfills, in oceans, flying out of the garbage truck in front of me as I write this column on my PDA.
- |
  

- "Then they go and complain about the tiny, tiny chemicals inside, like this bisphenol-A thing they made up\x97chemicals they can't even see!"
- |
  

- Or pronounce!
- |
  

- So which is it?
- |
  

- Unsightly gobs or invisible fake chemicals?
- |
  

- The environmental movement is riddled with these moral contradictions.
- |
  

- "That means we can all relax: plastics are good for us."
- |
  

- Right now I'm eating General Tso's chicken out of a plastic container with a plastic fork using my non-PDA-typing hand.
- |
  

- Knees are working the steering wheel, if you're wondering.
- "Which reminds me: food."
- |
  

- For as long as humans have been alive, they have been eating food.
- |
  

- Recent evidence from the national academies shows that animals also eat food.
- |
  

- Many, I'm told, on a daily basis.
- |
  

- We can either crank up the Radiohead, put on our dark sunglasses and long-sleeved T-shirts, and throw garbage cans at Monsanto GMO headquarters or we can get our next meal with the best modified genes science has to offer.
- |
  

- By the way, as with bisphenol, You Can't.
- |
  

- Even.
- |
  

- See.
- |
  

- Genes.
- |
  

- What are they fighting against?
- |
  

- Plus, a new study, conducted this past weekend on Dan and Marlene's new deck, shows that tofu dogs taste like crap.
- Did you know that steering SUVs with your knees saves gas?
- |
  

- Did I say that yet?
- |
  

- It's harder to do in smaller cars, because leg room sucks.
- |
  

- One more reason the anti-SUV hysteria is just that.
- |
  

- Smaller cars also waste gas, because you have to drive them so much more to haul all your stuff.
- |
  

- When we got our other SUVs, we could haul three times as much garbage to the river and twice as many recyclables, if we had them.
- |
  

- But the Connie Cleanwaters don't want you to know that.
- Also, mercury is good for you.
- |
  

- Drink it up.
- |
  

- At least one study (hat tip to John T.) found that mercury is our best way to determine the temperature of the earth.
- |
  

- And yet tree huggers would have you believe that the earth is warming.
- |
  

- Ironically, the only way they could know this is by using the same mercury-filled thermometers they apparently think are bad for you.
- You don't have to worry about global warming anyway.
- |
  

- Some are now arguing that what we lose in cooler temps we make up for with less spending on clothes.
- |
  

- Bad news for Old Navy; good news for Americans and the environment.
- |
  

- It all evens out economically, just like in that  Seinfeld  episode where everything always evens out.
- |
  

- Can you believe that Kramer guy?
- |
  

- What a racist!
- Incidentally, racism is no longer a problem.
- |
  

- They caught Kramer.
- |
  

- And that one guy is running for president.
- |
  

downcase_name: an.anti.environmentalist...hummer_by.benjamin.cohe
author: By Benjamin Cohen
title: An Anti-Environmentalist Drafts His Next Newspaper Column While Eating Takeout and Driving His Hummer
text: "BY  BENJAMIN COHEN\n\
  - - - -\n\
  The good news is in: Plastics are great. Stop your bitching. I've been reading all the research and the problem is you. No, I'm not anti-environment; I'm anti-environmentalist. It's like that line, right? You shoot messengers?\n\
  This whole thing, I'm with crack reporter John Tierney, our friend at the  Times  over there debunking pointless concerns from Crocs-wearing pansies. Those alarmists have complained for years that unsightly gobs of plastic bags won't deteriorate for centuries. In landfills, in oceans, flying out of the garbage truck in front of me as I write this column on my PDA. Then they go and complain about the tiny, tiny chemicals inside, like this bisphenol-A thing they made up\x97chemicals they can't even see! Or pronounce! So which is it? Unsightly gobs or invisible fake chemicals? The environmental movement is riddled with these moral contradictions. That means we can all relax: plastics are good for us. Right now I'm eating General Tso's chicken out of a plastic container with a plastic fork using my non-PDA-typing hand. Knees are working the steering wheel, if you're wondering.\n\
  Which reminds me: food. For as long as humans have been alive, they have been eating food. Recent evidence from the national academies shows that animals also eat food. Many, I'm told, on a daily basis. We can either crank up the Radiohead, put on our dark sunglasses and long-sleeved T-shirts, and throw garbage cans at Monsanto GMO headquarters or we can get our next meal with the best modified genes science has to offer. By the way, as with bisphenol, You Can't. Even. See. Genes. What are they fighting against? Plus, a new study, conducted this past weekend on Dan and Marlene's new deck, shows that tofu dogs taste like crap.\n\
  Did you know that steering SUVs with your knees saves gas? Did I say that yet? It's harder to do in smaller cars, because leg room sucks. One more reason the anti-SUV hysteria is just that. Smaller cars also waste gas, because you have to drive them so much more to haul all your stuff. When we got our other SUVs, we could haul three times as much garbage to the river and twice as many recyclables, if we had them. But the Connie Cleanwaters don't want you to know that.\n\
  Also, mercury is good for you. Drink it up. At least one study (hat tip to John T.) found that mercury is our best way to determine the temperature of the earth. And yet tree huggers would have you believe that the earth is warming. Ironically, the only way they could know this is by using the same mercury-filled thermometers they apparently think are bad for you.\n\
  You don't have to worry about global warming anyway. Some are now arguing that what we lose in cooler temps we make up for with less spending on clothes. Bad news for Old Navy; good news for Americans and the environment. It all evens out economically, just like in that  Seinfeld  episode where everything always evens out. Can you believe that Kramer guy? What a racist!\n\
  Incidentally, racism is no longer a problem. They caught Kramer. And that one guy is running for president.\n\
  - - - -"
date: 9/3/08
article_url: http://mcsweeneys.net/2008/9/3cohen.html
article_size: 3099
