--- 
lines: 
- BY  CHRIS GUTHRIE
- |
  

- The primary action item for the results-driven dodgeball player is to maximize the net performance potential of your dodgeball team.
- |
  

- A proactive participant should touch base with Kenny Satterfield and Jeff Gideon before teams are selected, or at least stand next to them in line, since everyone knows they are the hardest-throwing resources in the fourth grade.
- |
  

- Embrace and extend upon the strengths of the shorter resources, especially Tommy Mazzarella, for he can crouch really low and is therefore a difficult target.
- |
  

- Remember that in most cases knowledge transfer is moot during the shorter morning recess, so there is no reason to reintegrate Mary Hartney and the other stupid girls syncing up in the corner.
- |
  

- They will quickly be dehired.
- Incentivize your teammates.
- |
  

- Remind them that taking their dodgeball to the next level requires 100 percent focus on the current milestone, which has nothing to do with the farting noise Bradley Parnell can make with his hands.
- |
  

- But don't be afraid to adjust to their skill set.
- |
  

- Allow the slower-footed resources to leverage their arms from the sideline.
- |
  

- Don't let tagged players fall out of the loop, unless they are Mary Hartney and her friend Beth, who usually outsource themselves to the bathroom anyway.
- |
  

- As your team is downsized, take ownership of remaining players by inventorying your resources and then staying away from them, because the other kids usually throw into a group.
- WTAWTAW, even if the will belongs to only you and your two remaining resources, and the way requires you to go ahead and throw at your opponent's head when Mrs. Schobel blows the two-minute whistle, leading Neill Mardigian to leverage the ball over the handball court.
- |
  

- Diminishing numbers and a time-centered strategy can bottleneck your opponent's objective as well, so stall if you're about to lose.
- |
  

- Likewise, a catch-centered strategy can allow you to re-engineer your results and take ownership of the center line.
- |
  

- Remain functional when all responsive contingencies have been exhausted and don't hesitate to call your opponent a "fruitcake" during his throw, even if he hates being called that and warned you not to call him that again during morning lineup.
- Hitting the dodgeball home run requires an integrated corporate vision, with limited disconnect and really fast reflexes.
- |
  

- It may also require you to give the ball to one of the bigger resources, if your arm isn't a strong metric.
- |
  

- As you play, keep in focus the wellness you will accumulate during reading group as the key enabler and don't surrrender to the challenge, unless both Kenny Satterfield and Jeff Gideon are on the other team, because they always win.
- |
  

downcase_name: effective.application.str.odgeball_by.chris.guthri
author: By Chris Guthrie
title: Effective Application Strategies for Mrs. Schobel's Morning-Recess Dodgeball
text: |-
  BY  CHRIS GUTHRIE
  - - - -
  The primary action item for the results-driven dodgeball player is to maximize the net performance potential of your dodgeball team. A proactive participant should touch base with Kenny Satterfield and Jeff Gideon before teams are selected, or at least stand next to them in line, since everyone knows they are the hardest-throwing resources in the fourth grade. Embrace and extend upon the strengths of the shorter resources, especially Tommy Mazzarella, for he can crouch really low and is therefore a difficult target. Remember that in most cases knowledge transfer is moot during the shorter morning recess, so there is no reason to reintegrate Mary Hartney and the other stupid girls syncing up in the corner. They will quickly be dehired.
  Incentivize your teammates. Remind them that taking their dodgeball to the next level requires 100 percent focus on the current milestone, which has nothing to do with the farting noise Bradley Parnell can make with his hands. But don't be afraid to adjust to their skill set. Allow the slower-footed resources to leverage their arms from the sideline. Don't let tagged players fall out of the loop, unless they are Mary Hartney and her friend Beth, who usually outsource themselves to the bathroom anyway. As your team is downsized, take ownership of remaining players by inventorying your resources and then staying away from them, because the other kids usually throw into a group.
  WTAWTAW, even if the will belongs to only you and your two remaining resources, and the way requires you to go ahead and throw at your opponent's head when Mrs. Schobel blows the two-minute whistle, leading Neill Mardigian to leverage the ball over the handball court. Diminishing numbers and a time-centered strategy can bottleneck your opponent's objective as well, so stall if you're about to lose. Likewise, a catch-centered strategy can allow you to re-engineer your results and take ownership of the center line. Remain functional when all responsive contingencies have been exhausted and don't hesitate to call your opponent a "fruitcake" during his throw, even if he hates being called that and warned you not to call him that again during morning lineup.
  Hitting the dodgeball home run requires an integrated corporate vision, with limited disconnect and really fast reflexes. It may also require you to give the ball to one of the bigger resources, if your arm isn't a strong metric. As you play, keep in focus the wellness you will accumulate during reading group as the key enabler and don't surrrender to the challenge, unless both Kenny Satterfield and Jeff Gideon are on the other team, because they always win.
  - - - -
date: 10/19/04
article_url: http://mcsweeneys.net/2004/10/19guthrie.html
article_size: 2690
