--- 
lines: 
- BY  KATE KERSHNER
- |
  

- Please note the following points that shall be adhered to on Kate Kershner's Holiday Visit Home Tour.
- |
  

- It is in the best interest of the VENUE (i.
- |
  

- JIM and CAROL KERSHNER'S rancher on 34th St.
- |
  

- VENUE ever wishes to see the TALENT (i.
- |
  

- KATE KERSHNER) come back after the 2006 Tour.
- |
  

- This written agreement must be agreed upon and given no amendment unless specifically addressed with the TALENT.
- Please also note that this rider would be unnecessary were it not for the now-canceled OPENING ACT (i.
- |
  

- Mike Kershner, brother and ultimate betrayer of TALENT), who got a little too popular (i.
- |
  

- Tour this year.
- |
  

- TALENT, who no longer trusts anyone after OPENING ACT left for his own fancy TOUR and new VENUE, feels it best to have everything on paper.
- |
  

- Although this document is not legally binding, it does work in accordance with the strict legality of the OFFICIAL CONTRACT (i.
- |
  

- Kate Kershner's birth certificate, verifying JIM and CAROL KERSHNER as Parents, and thus responsible for all future happiness).
- "LOAD IN:"
- TALENT arrives alone.
- |
  

- Upon arrival, do not ask where CREW is.
- |
  

- Do not get clever by saying boyfriend/your friend/special friend instead of CREW.
- |
  

- Consider VENUE forewarned that when TALENT feels VENUE can act appropriately around CREW, TALENT will bring CREW.
- |
  

- So TALENT will be arriving alone.
- TALENT will be bringing one (1) duffel bag full of laundry, and TALENT doesn't want to hear she's too old for this.
- |
  

- TALENT will do laundry herself.
- |
  

- Unless VENUE, you know, was already planning on doing some anyway, in which case it would probably be easier if VENUE just threw it in with whatever VENUE is doing.
- |
  

- No big deal.
- Upon LOAD IN, the following should be placed in DRESSING ROOM (i.
- |
  

- "TALENT'S former bedroom, now renamed CAROL'S NEW \"PURPLE ROOM,\" painted to accompany VENUE'S new \"BLUE ROOM,\" which makes TALENT ache for a time when a room in VENUE could be beige):"
- |
  

- Bottle of Vodka
- |
  

- Bottle of Tonic, and not the diet tonic that VENUE usually buys.
- |
  

- TALENT doesn't appreciate what VENUE is trying to say when VENUE only buys TALENT diet tonic water.
- |
  

- Bath towel, long enough to be crammed under bottom of door
- |
  

- Fan, which should be facing out the window
- Smoke detector in room MUST BE DISABLED before LOAD IN.
- |
  

- No drinking glasses necessary.
- TALENT will take thirty (30) minutes to "put stuff away" in DRESSING ROOM after load in. VENUE should leave TALENT alone for those thirty (30) minutes, even if choking coughs can be heard. TALENT is fine. Upon TALENT exiting DRESSING ROOM, VENUE should be sensitive to the fact that TALENT might have trouble with simple appliances, proper conjugation in conversation, etc. Please recall Holiday Tour 2004, when TALENT made VENUE late for Christmas Eve Mass because it took TALENT approx. one half-hour to tie her shoe. Due to the fact that TALENT was wearing boots without laces. It'll be a lot like that. Be patient.
- "DURING DINNER SHOW:"
- It is our understanding that various other acts (i.
- |
  

- SPECIAL GUESTS) will be sharing the bill with TALENT during the Kate Kershner Holiday Visit Home Tour during the DINNER segment of our show.
- |
  

- The following is required of VENUE during DINNER, but also extends to SPECIAL GUESTS.
- "TOPICS THAT ARE OFF LIMITS WHEN TALKING TO TALENT:"
- |
  

- TALENT'S lack of reliable employment
- |
  

- TALENT'S lack of reliable relationships
- |
  

- The story of that time TALENT pretended to be suicidal when she was 7 years old so she could find out what therapy was like, unless TALENT chooses to tell anecdote herself.
- |
  

- No one but TALENT can tell that story with the proper context and complex nuances, and TALENT is sick sick sick of people fucking it up.
- |
  

- TALENT'S physical appearance, especially her hair color.
- |
  

- TALENT understands she has roots, and fails to see why VENUE must mention this at every occasion.
- |
  

- TALENT would be happy to amend the situation if VENUE would like to fork over $150 for a salon touchup.
- |
  

- No? That's what TALENT thought.
- |
  

- TALENT'S complicated financial situation
- |
  

- Probably best to avoid politics, books of a high-minded literary nature, foreign films, and music that doesn't have words.
- |
  

- TALENT feels stupid when these are discussed and accidentally lies about her knowledge of them, which makes TALENT feel bad and drink more.
- |
  

- "Keep in mind: Keeping TALENT happy is legally binding to VENUE in accordance with OFFICIAL CONTRACT."
- "RECOMMENDED TOPICS WHEN TALKING TO TALENT:"
- |
  

- Brokeback Mountain .
- |
  

- TALENT knows it came out last year, but TALENT just saw it for the second time and thinks she has some pretty interesting things to say about it.
- |
  

- Celebrities.
- |
  

- Especially any anecdotes about meeting them/seeing them somewhere.
- |
  

- Jake Gyllenhaal/Heath Ledger sightings will be rewarded with robust conversation.
- "The following should be placed on or near the table at DINNER:"
- |
  

- Bottles of wine per person at table, preferably something cheap so VENUE doesn't bitch about how expensive it was during the course of the entire evening
- |
  

- Bowl of mashed potatoes, skin ON.
- |
  

- SKIN IS WHERE THE VITAMINS ARE.
- |
  

- Bowls of stuffing, one cornbread and one plain.
- |
  

- If there is so much as half a raisin in the stuffing, TALENT will immediately leave the table and possibly the city.
- More food, at the VENUE'S discretion.
- |
  

- Please check ahead with TALENT, however.
- |
  

- And make sure not to have anything with honey.
- |
  

- TALENT doesn't mind the taste, but it leaves her fingers sticky, which annoys her.
- "LOAD OUT:"
- "TALENT will require the following items on leaving the premises:"
- |
  

- Leftover container of every dish served at dinner
- |
  

- Flask of alcohol, filled from VENUE'S liquor cabinet
- |
  

- Pack of double-A batteries, provided by VENUE
- |
  

- Copy of  Sports Illustrated , provided by VENUE
- |
  

- Old hair dryer, provided by VENUE
- |
  

- Box of envelopes, provided by VENUE
- |
  

- Books that VENUE recommends, and provides
- |
  

- Duffel bag of clean clothes
- |
  

- Dollars, for travel expenses
- With all the TALENT'S demands met, we anticipate 2006 to be the best Holiday Visit Home Tour so far!
- |
  

downcase_name: production.rider.for.kate.ome.tour_by.kate.kershn1
author: By Kate Kershner
title: Production Rider for Kate Kershner's Holiday Visit Home Tour
text: |-
  BY  KATE KERSHNER
  - - - -
  Please note the following points that shall be adhered to on Kate
  Kershner's Holiday Visit Home Tour. It is in the best interest of the
  VENUE (i.e.: JIM and CAROL KERSHNER'S rancher on 34th St. and the
  inhabitants therein) that these demands be strictly followed, if the
  VENUE ever wishes to see the TALENT (i.e.: KATE KERSHNER) come back
  after the 2006 Tour. This written agreement must be agreed upon and
  given no amendment unless specifically addressed with the TALENT.
  Please also note that this rider would be unnecessary were it not for
  the now-canceled OPENING ACT (i.e.: Mike Kershner, brother and ultimate
  betrayer of TALENT), who got a little too popular (i.e.: a little too married) to come on Tour this year. TALENT, who no longer trusts anyone after OPENING ACT left for his own fancy TOUR and new VENUE, feels it best to have everything on paper. Although this document is not legally binding, it does work in accordance with the strict legality of the OFFICIAL CONTRACT (i.e.: Kate Kershner's birth certificate, verifying JIM and CAROL KERSHNER as Parents, and thus responsible for all future happiness).
  LOAD IN:
  TALENT arrives alone. Upon arrival, do not ask where CREW is. Do not
  get clever by saying boyfriend/your friend/special friend instead of
  CREW. Consider VENUE forewarned that when TALENT feels VENUE can act
  appropriately around CREW, TALENT will bring CREW. So TALENT will be
  arriving alone.
  TALENT will be bringing one (1) duffel bag full of laundry, and TALENT
  doesn't want to hear she's too old for this. TALENT will do laundry
  herself. Unless VENUE, you know, was already planning on doing some
  anyway, in which case it would probably be easier if VENUE just threw
  it in with whatever VENUE is doing. No big deal.
  Upon LOAD IN, the following should be placed in DRESSING ROOM (i.e.:
  TALENT'S former bedroom, now renamed CAROL'S NEW "PURPLE ROOM,"
  painted to accompany VENUE'S new "BLUE ROOM," which makes TALENT ache
  for a time when a room in VENUE could be beige):
  (1) Bottle of Vodka
  (1) Bottle of Tonic, and not the diet tonic that VENUE usually buys.
  TALENT doesn't appreciate what VENUE is trying to say when VENUE only
  buys TALENT diet tonic water.
  (1) Bath towel, long enough to be crammed under bottom of door
  (1) Fan, which should be facing out the window
  Smoke detector in room MUST BE DISABLED before LOAD IN. No drinking
  glasses necessary.
  TALENT will take thirty (30) minutes to "put stuff away" in DRESSING
  ROOM after load in. VENUE should leave TALENT alone for those thirty
  (30) minutes, even if choking coughs can be heard. TALENT is fine.
  Upon TALENT exiting DRESSING ROOM, VENUE should be sensitive to the
  fact that TALENT might have trouble with simple appliances, proper
  conjugation in conversation, etc. Please recall Holiday Tour 2004,
  when TALENT made VENUE late for Christmas Eve Mass because it took
  TALENT approx. one half-hour to tie her shoe. Due to the fact that
  TALENT was wearing boots without laces. It'll be a lot like that. Be
  patient.
  DURING DINNER SHOW:
  It is our understanding that various other acts (i.e.: SPECIAL GUESTS)
  will be sharing the bill with TALENT during the Kate Kershner Holiday
  Visit Home Tour during the DINNER segment of our show. The following
  is required of VENUE during DINNER, but also extends to SPECIAL
  GUESTS.
  TOPICS THAT ARE OFF LIMITS WHEN TALKING TO TALENT:
  1. TALENT'S lack of reliable employment
  2. TALENT'S lack of reliable relationships
  3. The story of that time TALENT pretended to be suicidal when she
  was 7 years old so she could find out what therapy was like,
  unless TALENT chooses to tell anecdote herself. No one but TALENT can
  tell that story with the proper context and complex nuances, and
  TALENT is sick sick sick of people fucking it up.
  4. TALENT'S physical appearance, especially her hair color. TALENT
  understands she has roots, and fails to see why VENUE must mention
  this at every occasion. TALENT would be happy to amend the situation
  if VENUE would like to fork over $150 for a salon touchup. No?
  That's what TALENT thought.
  5. TALENT'S complicated financial situation
  6. Probably best to avoid politics, books of a high-minded literary
  nature, foreign films, and music that doesn't have words. TALENT
  feels stupid when these are discussed and accidentally lies about her
  knowledge of them, which makes TALENT feel bad and drink more. Keep
  in mind: Keeping TALENT happy is legally binding to VENUE in
  accordance with OFFICIAL CONTRACT.
  RECOMMENDED TOPICS WHEN TALKING TO TALENT:
  1.  Brokeback Mountain . TALENT knows it came out last year, but
  TALENT just saw it for the second time and thinks she has some pretty
  interesting things to say about it.
  2. Celebrities. Especially any anecdotes about meeting them/seeing
  them somewhere. Jake Gyllenhaal/Heath Ledger sightings will be
  rewarded with robust conversation.
  The following should be placed on or near the table at DINNER:
  (2) Bottles of wine per person at table, preferably something cheap so
  VENUE doesn't bitch about how expensive it was during the course of
  the entire evening
  (1) Bowl of mashed potatoes, skin ON. SKIN IS WHERE THE VITAMINS ARE.
  (2) Bowls of stuffing, one cornbread and one plain. If there is so
  much as half a raisin in the stuffing, TALENT will immediately leave
  the table and possibly the city.
  More food, at the VENUE'S discretion. Please check ahead with TALENT,
  however. And make sure not to have anything with honey. TALENT
  doesn't mind the taste, but it leaves her fingers sticky, which annoys
  her.
  LOAD OUT:
  TALENT will require the following items on leaving the premises:
  (1) Leftover container of every dish served at dinner
  (1) Flask of alcohol, filled from VENUE'S liquor cabinet
  (1) Pack of double-A batteries, provided by VENUE
  (1) Copy of  Sports Illustrated , provided by VENUE
  (1) Old hair dryer, provided by VENUE
  (1) Box of envelopes, provided by VENUE
  (3) Books that VENUE recommends, and provides
  (1) Duffel bag of clean clothes
  (50) Dollars, for travel expenses
  With all the TALENT'S demands met, we anticipate 2006 to be the best
  Holiday Visit Home Tour so far!
  - - - -
date: 12/22/06
article_url: http://mcsweeneys.net/2006/12/22kershner.html
article_size: 6118
