--- 
lines: 
- BY  STEVE SCHNEIDER
- |
  

- Cleave
- Conmix
- Commingle
- Interlard
- Fashion Into a Thick, Uniform Paste
- Engruel
- Rend Asunder
- Fragment
- Thresh With Surpassing Rapidity
- |
  

downcase_name: the.settings.that.would.b.f....._by.steve.schneide
author: By Steve Schneider
title: The Settings That Would Be On a Blender Today If the Blender Had Been Invented, Say, 100 Years Before Its Actual Invention Date of 1922
text: |-
  BY  STEVE SCHNEIDER
  - - - -
  Cleave
  Conmix
  Commingle
  Interlard
  Fashion Into a Thick, Uniform Paste
  Engruel
  Rend Asunder
  Fragment
  Thresh With Surpassing Rapidity
  - - - -
date: 5/2/05
article_url: http://mcsweeneys.net/2005/5/2schneider.html
article_size: 167
